
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


-- --------------------------------------------------------

--
-- Table structure for table `dhl_error_code`
--

CREATE TABLE IF NOT EXISTS `dhl_error_code` (
  `error_cde` char(50) NOT NULL,
  `message` text NOT NULL,
  `error_desc` text NOT NULL,
  `id` int(11) unsigned NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=458 DEFAULT CHARSET=latin1 PACK_KEYS=1;

--
-- Dumping data for table `dhl_error_code`
--

INSERT INTO `dhl_error_code` (`error_cde`, `message`, `error_desc`, `id`) VALUES
('SV003', 'Cannot complete shipment request for consignee country. Please contact your technical service representative.', 'Consignee country not found', 2),
('SV004', 'Cannot complete shipment request for consignee country. Please contact your technical service representative.', 'Consignee country not active', 3),
('SV005', 'SV005: Cannot complete shipment request for consignee country. Please contact your technical service representative.', 'Temporary ban on consignee country', 4),
('SV006a', 'Cannot complete shipment request for consignee country. Please contact your technical service representative.', 'Temporary ban on dutiable shipments to consignee country', 5),
('SV006b', 'Cannot complete shipment request for consignee country. Please contact your technical service representative.', 'Ban on dutiable shipments that exceed the declared value to the destination country', 6),
('SV007', 'Shipment weight exceeds limits for consignee country. For assistance call your customer service representative.', 'Piece dimensional weight exceeded error limit', 7),
('SV007a', 'Package weight exceeds limits for consignee name. Please contact your customer service representative.', 'Piece dimensional weight exceeded error limit', 8),
('SV007b', 'Total shipment weight exceeds limits for consignee country. Please contact your customer service representative.', 'Piece dimensional weight exceeded error limit', 9),
('SV008', 'Warning Note! Dimensions or weights may require special handling or add to transit time. Please contact your customer service representative.', 'WARNING: Piece dimensional weight exceeded warning limit', 10),
('SV009', 'Warning Note!  Shipment exceeded value limits for consignee country may require pre-approval and added transit time. Please contact your customer service representative.', 'WARNING: Shipment declared value exceeded normal limits', 11),
('SV010a', 'Service information not available. Check shipper Zip/postal code or city and resubmit. If this problem reoccurs contact your technical service representative.', 'Origin routing code could not be determined', 12),
('SV010b', 'Service information not available. Check shipper Zip/postal code or city and resubmit. If this problem reoccurs contact your technical service representative.', 'Postal code not provided to determine the origin routing code.', 13),
('SV010c', 'Service information not available. Check shipper Zip/postal code or city and resubmit. If this problem reoccurs contact your tecnhical service representative.', 'Postal code invalid for the purpose of identifying the origin routing code', 14),
('SV011a', 'Cannot determine destination service. Check recipient information and resubmit. If this problem reoccurs contact your technical service representative.', 'Destination routing code could not be determined', 15),
('SV011b', 'Cannot determine destination service. Check recipient?s Zip/postal code or city and resubmit. If this problem reoccurs contact your technical service representative.', 'Postal code not provided to determine the destination routing code', 16),
('SV011c', 'Cannot determine destination service. Check recipients Zip/postal code or city and resubmit. If this problem reoccurs contact your technical service representative.', 'Postal code invalid for the purpose of identifying the destination routing code', 17),
('SV012a', 'Account number Shipper Account Number incorrect or invalid. Correct account number and resubmit. If this problem reoccurs contact your technical service representative.', 'Shipper account number was not found in the billing records', 18),
('SV012b', 'Account number Shipper Account Number incorrect or invalid. Correct account number and resubmit. If this problem reoccurs contact your technical service representative.', 'Shipper account is not a domestically billed shipper account', 19),
('SV012c', 'Account number Shipper Account Number incorrect or invalid. Correct account number and resubmit. For assistance call your technical service representative.', 'Shipper account is for internal use only', 20),
('SV012d', 'Account number Shipper Account Number incorrect or invalid. Correct account number and resubmit. For assistance call your technical service representative.', 'Shipper account is for inbound use only', 21),
('SV012e', 'Cannot process using account number Shipper Account Number. Please contact your technical service representative.', 'Shipper account is marked for deletion', 22),
('SV012f', 'Account number Shipper Account Number incorrect or invalid. Please correct account number and resubmit. If this problem reoccurs contact your technical service representative.', 'Shipper account is not in good credit standing', 23),
('SV013a', 'Account number Shipper Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative.', 'Shipper account number is not valid', 24),
('SV013b', 'Account number Shipper Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative.', 'Shipper account number is not valid', 25),
('SV013c', 'Account number Shipper Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative.', 'Shipper account number is not valid', 26),
('SV013d', 'Account number Shipper Account Number incorrect or invalid.  Correct account number and resubmit. For assistance call technical service representative.', 'Shipper account number is not valid', 27),
('SV014a', 'Account number Billing Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative.', 'Shipment bill-to account number was not found in the billing records', 28),
('SV014b', 'Account number Billing Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative.', 'Shipment bill-to account is not a domestically billed shipper account', 29),
('SV014c', 'Account number Billing Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative.', 'Shipment bill-to account is for internal use only', 30),
('SV014d', 'Account number Billing Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative.', 'Shipment bill-to account is for inbound use only', 31),
('SV014e', 'Account number Billing Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative.', 'Shipment bill-to account is not in good credit standing', 32),
('SV015a', 'Account number Billing Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative.', 'billing account number is not valid', 33),
('SV015b', 'Account number Billing Account Number incorrect or invalid. Correct the account number and resubmit. For assistance call technical service representative.', 'billing account number is not valid', 34),
('SV015c', 'Account number Billing Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative.', 'billing account number is not valid', 35),
('SV015d', 'Account number Billing Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative.', 'billing account number is not valid', 36),
('SV016a', 'Account number Duty Tax Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative.', 'Duty bill-to account number was not found in the billing records', 37),
('SV016b', 'Account number Duty Tax Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative.', 'Duty bill-to account is for internal use only', 38),
('SV016c', 'Account number Duty Tax Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative.', 'Duty bill-to account is for inbound use only', 39),
('SV016d', 'Account number Duty Tax Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative.', 'Duty bill-to account is not in good credit standing', 40),
('SV017a', 'Account number Duty Tax Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative.', 'billing account number is not valid', 41),
('SV017b', 'Account number Duty Tax Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative', 'billing account number is not valid', 42),
('SV107c', 'Account number Duty Tax Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative.', 'billing account number is not valid', 43),
('SV017d', 'Account number Duty Tax Account Number incorrect or invalid. Correct account number and resubmit. For assistance call technical service representative.', 'billing account number is not valid', 44),
('SV018', 'System failure. Resubmit your request at later time. If urgent shipment , please resubmit your airwaybill or contact your technical service representative.', 'Cannot complete the validation due to system failure', 45),
('SV019', 'Account number Billing Account Number is for international recipient billing only. Correct billing option. For assistance call customer service representative.', 'Payment method was not bill recipient', 46),
('SV021', 'Account number Billing Account Number not available for shipping to consignee country. Change billing option or account number. For assistance call customer service representative.', 'Invalid transport collect billing option (shipments to ship-to country cannot be billed to recipient)', 47),
('SV022', 'Account number Billing Account Number is for international billing. Correct account or destination and resubmit. For assistance call your customer service representative.', 'International country was not specified', 48),
('SV023a', 'Duty and taxes charges for consignee country must be billed to the recipient. Please select recipient duty payment option and resubmit. For assistance call customer service representative.', 'Billing option not available for the destination country', 49),
('SV023b', 'Duty charges must be billed to the recipient in the city of consignee. Please correct the duty payment option. For assistance call customer service representative.', 'Billing option not available for the specific service area of the destination country', 50),
('SV024', 'Account number Billing Account Number cannot be usedfor duties. Specify another payment option or "recipient" billing for duties. For assistance call customer service representative', 'Invalid duty payment option', 51),
('SV025a', 'Shipment not accepted for Transport Collect. Shipping charges not determined. Please contact your customer service representative.', 'Shipping charges not determined', 52),
('SV025b', 'Shipment not accepted for Transport Collect. Shipping charges not determined. Please contact your customer service representative.', 'Shipping charges not determined', 53),
('SV025c', 'Shipment not accepted for Transport Collect. Shipping charges not determined. Please contact your customer service representative.', 'Shipping charges not determined', 54),
('SV026', 'Insured value exceeds the declared value. Adjust insured or declared value accordingly. For assistance call your customer service representative.', 'Insured value exceeds 110% of the declared value', 55),
('SV027a', 'Shipment date has passed. Correct shipment date and resubmit. If this problem reoccurs contact your technical service representative.', 'Current date at the origin service area is already more than one day past the requested ship date', 56),
('SV027b', 'Shipment scheduled too far in the future. Correct the shipment date to less than 10 days and resubmit. If this problem reoccurs contact your technical service representative.', 'Requested date is more than 10 days from the current date at the origin service area', 57),
('SV028', 'Account number will not support door to airport and airport to airport service. Select another service or account number. Please contact your customer service representative.', 'Invalid Door-To option', 58),
('SV029', 'Service Name could not be resolved for given Station. Please contact your technical service representative.', 'billing account number invalid', 59),
('SV030', 'System failure. Please contact your technical service representative.', 'System unavailable error', 60),
('SV031', 'Warning Note! Your Account is a Cash Customer type account. Please contact your customer service representative.', 'Account type invalid.', 61),
('SV032', '[SV032] Error - Saturday delivery is not available to this destination.  Remove this option and re-submit your shipment.', 'Saturday delivery is not available for the specified destination.', 62),
('SV033', 'TDD/Jumbo/Jumbo Junior products should not be used in conjunction with 95/96 account numbers', 'Jumbo product cannot be used with IMP account.', 63),
('SV034a', 'Sorry, our system is not able to assign Piece IDs to your shipment at the moment. Please try again later or call our DHL Customer Service Hotline for furhter assistance.', 'Piece IDs not sufficient error', 64),
('SV034b', 'Sorry, there are insufficient Piece IDs to be assigned to your shipment at the moment. Please try again later or call our DHL Customer Service Hotline for furhter assistance.', 'Piece IDs range is exhausted.', 65),
('SV035', '[SV035] We are unable to service this ZIP code. Please contact your DHL sales representative for further assistance ', 'Postcode is incorrect and failed in routing', 66),
('SV036', 'Your shipper account number cannot be used for shipments originating in the US.  Enter another account and resubmit or call technical support representative.', 'Shipper account number is not correct', 67),
('SV037', 'Your billing account number cannot be used for shipments originating in the US.  Enter another account and resubmit or call technical support representative.', 'Billing account number is not correct.', 68),
('SV038', 'Your duty tax account number cannot be used for shipments originating in the US.  Enter another account and resubmit or call technical support represenative.', 'Duty tax account number is not correct.', 69),
('SV039', 'Your billing account number cannot be used.  Enter another account and resubmit or call technical support representative.', 'Billing account number is not correct.', 70),
('SV040', 'Your duty tax account number cannot be used.  Enter another account and resubmit or call technical support representative.', 'Duty tax account number is not correct.', 71),
('SV041', 'Your billing account number is for international billing only.  Correct the account or destination and resubmit.', 'Billing account number is not correct.', 72),
('SV042', 'Shipments to the destination country cannot be billed to the recipient.  Change the payment option and resubmit.', 'Shipment to the destination country is not supported for the payment option of Recipient.', 73),
('SV044', '[SV044] The insured value exceeds the declared value of the package. Please correct and re-submit.', 'Insured value exceeds the declared value of the shipment.', 74),
('SV045', 'This is an onforwarded destination. Your shipment can take 1 or 2 days more to be delivered', 'Additonal delivery days required for required destination.', 75),
('SV046', 'NOTE! The number of packages in your shipment, the dimensions, or the weights may require special handling or may add to transit time', 'The packages require special handling.', 76),
('SV047', 'Your package size or weight exceeds the limits for the destination country.  For assistance, please call technical support representative.', 'The package size or weight exceeds the destination country''s limit.', 77),
('SV048', 'NOTE! The dimension or weight of your shipment may require special handling or may add to transit time.', 'The shipment required special handling as oversize.', 78),
('SV049', 'Your shipment was not accepted.  The weight of one or more SED Line exceeds limit.  For assistance, call technical support representative.', 'The shipment is not accepted as exceeds limits.', 79),
('SV050', '[SV050] Local Product Code not configured for the country. Please contact technical service representative.', 'Local product code is not allowed for the country.', 80),
('SV051', '[SV051] POD is not available for shipments to destination country. Please unselect the POD option and resubmit.', 'POD is not supported for the shipment to the specified destination country.', 81),
('SV052', 'Total Declared Value must be same per the total of all individual item''s value in export line item section. Please update it and re-try.', 'The total of all individual''s value must be same as per the total declared value.', 82),
('SV053', 'The global schema used for this service is incorrect. Please use the latest global schema version that published in XML Services toolkit.', 'The schema version used in incorrect.', 83),
('SV054', 'Shipment is created with an unauthorized Shipper Account Number. Please contact DHL Administrator.', 'Shipper Account number used in shipment is not authorized.', 84),
('SV055', 'Shipment is created with an unauthorized Billing Account Number. Please contact DHL Administrator.', 'Billing Account number used in shipment is not authorized.', 85),
('SV056', 'Shipment is created with an unauthorized Duty Account Number. Please contact DHL Administrator.', 'Duty Account number used in shipment is not authorized.', 86),
('SV057', 'Shipment is created with an unauthorized Registered Account Number. Please contact DHL Administrator.', 'Registered Account number used in shipment is not authorized.', 87),
('SV058', 'Shipment is created with DutyPaymentType Recipient(R), an IMP account must be entered. Please contact your technical service representative for assistance.', 'For shipment with Duty Payment Type value of ''R'', IMP account must be used.', 88),
('107', 'Incorrect or Incomplete Input Parameters', 'Incorrect or Incomplete Input Parameters', 89),
('108', 'System Unavailable', 'System Unavailable', 90),
('111', 'Error in parsing request XML', 'Error in parsing request XML', 91),
('112', 'Request type could not be identified', 'Request type could not be identified', 92),
('113', 'The same special service cannot be requested more than once', 'The same special service cannot be requested more than once', 93),
('114', 'Wrong packaging Type entered. Packaging type can only be CP.', 'Wrong packaging Type entered. Packaging type can only be CP.', 94),
('123', 'Query User Profile System Unavailable', 'eCom backend - Query User Profile service is not available', 95),
('124', 'DCT System Unavailable', 'DCT application is not available', 96),
('150', 'Error in the Data', 'The data is not Valid', 97),
('151', 'Mandatory Required error', 'Mandatory Field Missing Error', 98),
('152', 'Conditional Required Error', 'Condition Field Missing Error', 99),
('153', 'Recurrence Error', 'Data Recurrence Error', 100),
('154', 'Value Error', 'Value Provided is wrong', 101),
('155', 'Type Error', 'Type of data is wrong', 102),
('156', 'Length Error', 'The length of the value is wrong', 103),
('157', 'Format Error', 'The format of the value is wrong', 104),
('158', 'Shipment from Specified Country is not Supported', 'Shipment cannot originate from this country', 105),
('211', 'Please contact DHL representative', 'DHL Internal Error', 106),
('PLT002', 'DocImages is required for Paperless Trade (PLT) shipments.', 'Paperless trade (PLT) shipment is only available for:\n1) dutiable shipment\n<IsDutiable> element must contain value of ?Y?\n2) <Dutiable> element must be included\n3) <SpecialServiceType> element must contain value of ?WY?\n4) <DocImages> element must contain the commercial invoice or other supporting document images required for Customs clearance (unless <UseDHLInvoice> = ?Y?)', 107),
('PLT003', 'The origin country does not support Paperless shipment service. Please contact DHL representative for further information or resubmit as regular shipment.', 'This is warning message if the shipper country does not support PLT shipment and it will be processed as regular shipment without WY Paperless Trade service.', 108),
('PLT004', 'You are not subscribed for Paperless shipment service. Please contact your DHL technical representative for Paperless shipment subscription.', 'If the client is not subscribed for PLT shipmet service.For <PLTStatus> field value of ?D? ? De-registered', 109),
('PLT005', 'Paperless shipment is suspended. Please contact your DHL technical representative for reactivation.', 'If the <PLTStatus> field value is ?S? ? Suspended, XML-PI Shipment Validation service will not allow to proceed with the shipment flow and return a error message to the XML-PI client', 110),
('PLT006', 'Paperless shipment service is not allowed for one of these reasons: Shipper or receiver country doesn''t support Paperless Service, the product selected doesn''t support Paperless or the declared value entered is greater than the allowed limit. Please contact DHL representative for further information or resubmit as regular shipment.', 'PLT capability failed due to:\n1) Shipper or receiver country does not support Paperless Trade (WY)\n2) the selected product does not support Paperless Trade (WY)\n3) delcared value is exceeded the allowed value limit', 111),
('PLT007', 'The total image sizes exceeded the maximum image size for Paperless shipment. Please check and resubmit with correct request message.', 'The total document images for PLT shipment is exceeded the maximum images size in XMLPI application.', 112),
('RG001', 'eCom backend Registration service is temporary not available. Please resubmit your request later.', 'Registration service is having a problem that prevents processing of the registration request. Registration cannot occur.', 113),
('RG002', 'eCom backend Registration Service ? account validation process is temporary not available. Please resubmit your request later.', 'The account validation service is having a problem that prevents processing of the registration request. Registration cannot occur.', 114),
('RG003', 'eCom backend Registration service ? Routing process is temporarily not available. Please resubmit your request later.', 'The routing service is having a problem that prevents processing of the registration request. Registration cannot occur.', 115),
('RG004', 'Registration failed. Registration information is incomplete or invalid. Please check the registration information and resubmit your request again', 'At least one item in the registration request is either missing or has an invalid value. Registration is rejected.', 116),
('RG005', 'Registration failed. The software or data version is invalid. Please contact your DHL technical service representative for further assistance. ', 'The software / data version is not acceptable for registration. Registration is rejected.', 117),
('RG006', 'Registration failed. Your eCom Site ID is invalid.  Please contact your DHL technical service representative for further assistance.', 'Site ID has a ?revoked? status. Re-registration is rejected.', 118),
('RG007', 'Registration failed. It is not a valid location within US. Please contact your DHL technical service representative for further assistance.', 'User?s location is not in the USA. Registration is rejected', 119),
('RG008', 'Registration failed. Invalid Zip or Postal Code for the Country. Please correct and resubmit. For assistance, please contact your DHL technical service representative for further assistance', 'There is no DHL service area code for the shipper and/or pickup address. Registration rejected.', 120),
('RG009', 'Registration failed. Different shipper and pickup address is not allowed. Please correct and resubmit. For assistance, please contact your DHL technical service representative for further assistance.', 'The shipper address and pickup address have different service area codes. Registration cannot occur.', 121),
('RG010', 'Account number not found. Please contact your DHL technical service representative for further assistance', 'Account number specified by the user was not found in the NBC records. Registration cannot occur.', 122),
('RG011', 'Invalid account Number. Please correct and resubmit your request again. If this problem reoccurs contact your DHL technical service representative.', 'Account number specified is not a domestically billed account. Registration cannot occur.', 123),
('RG012', 'Invalid account number. Please correct and resubmit your request again. If this problem reoccurs contact your DHL technical service representative. ', 'Account number specified is for internal use only. Registration cannot occur.', 124),
('RG013', 'Invalid account number. Please correct and resubmit your request again. If this problem reoccurs contact your DHL technical service representative.', 'Account number specified by the user is restricted to ?inbound shipments only?. Registration cannot occur.', 125),
('RG014', 'Invalid account number. Please correct and resubmit your request again. If this problem reoccurs contact your DHL technical service representative.', 'The credit status of the account number specified by the user is not in ?good standing? or ?removed from credit suspension?.', 126),
('RG018', 'Registration failed. eCom Site ID is invalid. Please contact your DHL technical service representative.', 'Re-registration?s site ID not found in the database.', 127),
('RG019', 'Registration failed. Invalid account number. Please correct and resubmit your request again. If this problem reoccurs contact your DHL technical service representative.', 'Account validation cannot be completed', 128),
('RG020', 'Invalid account number due to invalid account type. Please correct and resubmit your request again. If this problem reoccurs contact your DHL technical service representative.', 'Account type is unknown', 129),
('RG021', 'Registration failed. Invalid postcode. Please resubmit after checking the zip or postal code and city name. If this problem reoccurs contact your DHL technical service representative.', 'Invalid postal code', 130),
('RG022', 'Registration failed. City and zip or postal code does not match. Please correct and resubmit. If this problem reoccurs contact your DHL technical service representative. ', 'City not found in Routing service', 131),
('RG023', 'eCom backend Registration service ? Account validation process is encountering some technical problem. Please resubmit your request at a later time. If this problem reoccurs contact your DHL technical service representative.', 'Account validation service can not be located', 132),
('RG024', 'eCom backend Registration service database is encountering some technical problem. Please resubmit your request at a later time. If this problem reoccurs contact your DHL technical service representative. ', 'eCom backend database error', 133),
('RG025', 'Cash Account not allowed. Please contact your DHL customer service representative. ', 'Cash Account not allowed.', 134),
('RG026', 'The eCom Site ID is unable to process Registration. Please contact your DHL technical representative.', 'eCom backend is not able to locate the pickup location ', 135),
('RG027', 'Registration failed. The billing type for your account is invalid to register.  Enter another account and resubmit or you?re your DHL technical representative.', 'Billing type for account is invalid. ', 136),
('RG028', 'Invalid eCom Site ID. Please contact your DHL technical representative for assistance.', 'Site Id not found. Unable to retrieve the PLT Status.\n\nThe site Id is invalid.', 137),
('QAB001', 'Way Bill Number provided in the request is not found in eCom backend data base.', 'Waybill number in image upload request is not available in backend database.', 138),
('QAB002', 'Image Upload is not supported for non-PLT shipment.', 'Image upload service is not available for non-PLT shipment.', 139),
('LG200001', 'Account not white-listed for ODD service; please contact your DHL account manager. ', 'Shipper account number not in ODD Shipper Account White List.', 140),
('LG200002', 'ODD is not deployed in this country. ', 'Shipment?s destination country is not ODD deployed country.', 141),
('LG200004', 'ODD Shipper Account Number field is required and waybill number is not exists in ODD. Please provide the Shipper Account Number. ', 'Shipper account number is required and waybill not found in ODD.', 142),
('LG200008', 'SHIPPER does not have access to GenType : <Gentype> ', 'When SHIPPER tries to get URL with GenType other than DeliveryOpt and ShpDeliveryOpt.', 143),
('LG005', 'ESB LinkGen Service is not able to query to fetch ODD URL. Please contact DHL for further assistance', 'ESB LinkGen service is not available', 144),
('GLOBAL_MASK_ERR_001', 'Invalid postal code of a shipper. Please provide a valid postal code for a shipper and resubmit.', 'Invalid shipper''s postal code', 145),
('GLOBAL_MASK_ERR_002', 'Invalid postal code of a consignee. Please provide a valid postal code for a consignee and resubmit.', 'Invalid receiver''s postal code', 146),
('GLOBAL_MASK_ERR_003', 'Invalid postal code of a place. Please provide a valid postal code for a place and resubmit.', 'Invalid place''s postal code', 147),
('GLOBAL_MASK_ERR_004', 'Shipment charges is mandatory for a CASH shipment. Please provide shipment charges and resubmit.', 'Shipment charges field is required for CASH shipment.', 148),
('GLOBAL_MASK_ERR_005', 'SiteID should be defined as cash Account OR Account should start with prefix cash. Please correct and resubmit.', 'Site ID must be cash account.', 149),
('DCT_GENERIC_ERR_001', 'DCT exception while processing shipment. Please contact help desk.', 'DCT Capability & Quote backend system not available.', 150),
('ESB_GLS_GENERIC_ERR_001', 'ESB GLS exception while processing shipment. Please contact help desk.', 'ESB GLS label rendering backend system not available.', 151),
('TEXT_TRANS_GENERIC_ERR_001', 'Exception at Transliterate Text. Please contact help desk.', 'ESB Transiliteraton backend system not available.', 152),
('DOC_MGMT_CONT_GENERIC_ERR_001', 'Exception at request synchronous of Document Management Controller. Please contact help desk.', 'ESB Document Management backend system not available.', 153),
('TRACKING_BACKEND_GENERIC_ERR_001', 'Remote exception retrieving GQSX remote, Creating GQSX request, Retrieving and Parsing GQSX Error response.', 'Tracking backend system not available.', 154),
('TRACKING_BACKEND_GENERIC_ERR_002', 'Exception at Track Known AWB From GQS_X.', 'Tracking backend system not available.', 155),
('TRACKING_BACKEND_GENERIC_ERR_003', 'Exception at Get AWB Response.', 'Tracking backend system not available.', 156),
('UNKNOWN_TRACKING_BACKEND_GENERIC_ERR_001', 'Failed to get GQS Remote object.', 'Tracking backend system not available.', 157),
('UNKNOWN_TRACKING_REMOTE_EXCEPTION', 'Remote exception at Unknown track by GQSX.', 'Tracking backend system not available.', 158),
('UNKNOWN_TRACKING_EXCEPTION', 'Exception at Unknown Tracking.', 'Tracking backend system not available.', 159),
('PIECE_ERR_001', 'Exception at Piece helper AWB Batch', 'Tracking backend system not available.', 160),
('PIECE_REMOTE_ERR_001', 'Exception at Piece helper AWB Batch', 'Tracking backend system not available.', 161),
('COMMERCIAL_INVOICE_HANDLER_ERR_001', 'Exception at Commercial Invoice Handler. Please contact help desk.', 'ESB GLS Custom Invoice rendering backend system not available.', 162),
('LABEL_SERVICE_HANDLER_001', 'Exception at Label Service Handler. Please contact help desk.', 'ESB GLS label rendering backend system not available.', 163),
('PICKUP_HANDLER_001', 'Exception at Pickup Handler. Please contact help desk.', 'Pickup backend system not available.', 164),
('BOOK_RATING_HANDLER_001', 'Ecom URL not found for Book Rating Handler. Please contact help desk.', 'Rating backend system not available.', 165),
('BOOK_RATING_HANDLER_002', 'Exception at Book Rating Handler. Please contact help desk.', 'Rating backend system not available.', 166),
('ESB_BOOKPICKUP_EXCEPTION', 'ESB BOOK exception while processing bookPickup. Please contact help desk.', 'Book Pickup backend system not available.', 167),
('ESB_MODIFYPICKUP_EXCEPTION', 'ESB BOOK exception while processing modifyPickup. Please contact help desk.', 'Modify Pickup backend system not available.', 168),
('ESB_CANCELPICKUP_EXCEPTION', 'ESB BOOK exception while processing cancelPickup. Please contact help desk.', 'Cancel Pikcup backend system not available.', 169),
('100', 'Error Validating incoming request XML  + <No Site ID provided> OR <No Password provided>', 'XML PI Site ID or password is not provided in the request xml', 170),
('102', 'No Shipper Reference', 'No value entered for Shipper Reference field', 171),
('104', 'No Shipper AccoutNumber', 'No value entered for Shipper Account Number field', 172),
('105', 'Invalid  Begin date <date> date must be of yyyy-MM-dd format', 'invalid date format for Begin date in Unknown tracking request.', 173),
('106', 'Too many Shipments Found.', 'Number of results returned exceeds maximum allowable limit set by  system.', 174),
('107', 'Incorrect or Incomplete Input Parameters', 'Request xml is not form correctly', 175),
('108', 'System Unavailable', 'If  the backend is unavailable and not exact error message is available (it will be the default message for tracking message).', 176),
('110', 'Invalid Date Range', 'End date has to be after Begin date', 177),
('111', 'Error in parsing request XML', 'The Request XML is failed against the XSD.', 178),
('118', 'The system could not determine the Air Way Bill Number(s) associated with this request. Please contact DHL for further assistance.', 'For Unknown Query: Any Exception occurred during parsing the response or any invalid data obtained from backend.', 179),
('119', 'The system could not determine the Shipper Reference associated with this request. Please contact DHL for further assistance.', 'For Unknown Query: Any Exception occurred during parsing the response or any invalid data obtained from backend.', 180),
('200', 'No AirwayBill Numbers received', 'No air waybill number being provided in the <AWBNumber> element', 181),
('201', 'Multiple shipper refrences are not supported.', 'Multiple references are not allowed', 182),
('202', 'Contact DHL to get information on the requested AWB Number', 'The air waybill number could be incorrect and contact DHL representative to check the tracked air waybill number', 183),
('207', 'Invalid AWBNumber', 'Waybill number is incorrect', 184),
('208', 'Call DHL for AWBNumber\n', 'Waybill number is not exists and please contact DHL representative', 185),
('209', 'No Shipments Found for AWBNumber\n', 'The tracked waybill number is not available', 186),
('210', 'Call DHL for LPNumber', 'License Plate number or Piece ID is not exists and please contact DHL representative', 187),
('RA001', 'The system was unable to determine the correct rate type for your shipment.                                                                                                      ', 'The system was unable to determine the correct rate type for your shipment.', 188),
('RA002', 'A rate could not be determined for the address specified. Please correct and re-submit. For assistance please call technical service representative.                            ', 'Shipper address information for this shipment is incomplete or invalid. Please correct your address information and resubmit.', 189),
('RA003', 'The system was unable to estimate charges for your shipment. For assistance please call customer service representative.                                                        ', 'The system was unable to estimate charges for your shipment. For assistance please call customer service representative.    ', 190),
('RA004', 'The shipper or billing account is not valid or is not appropriate for this usage. Change the account and resubmit.                                                               ', 'The shipper or billing account is not valid or is not appropriate for this usage. Change the account and resubmit', 191),
('RA005', 'The consignee country code is invalid. Please contact technical service representative.                                                                                          ', 'The consignee country code is invalid. Please contact technical service representative.                                                                                          ', 192),
('RA006', 'Your account rates are not available here. Please contact your DHL sales representative to obtain your special rates or call technical service representative.                   ', 'Your account rates are not available here. Please contact your DHL sales representative to obtain your special rates or call technical service representative.                   ', 193),
('RA007', 'We are unable to service this ZIP code. Please contact your DHL sales representative for further assistance.                                                                     ', 'We are unable to service this ZIP code. Please contact your DHL sales representative for further assistance.                                                                     ', 194),
('RA008', 'Cannot complete rating request for consignee country. Please contact your technical service representative.                                                                      ', 'Cannot complete rating request for consignee country. Please contact your technical service representative.                                                                      ', 195),
('RA009', 'Cannot complete rating request for consignee country. Please contact your technical service representative.                                                                      ', 'Cannot complete rating request for consignee country. Please contact your technical service representative.                                                                      ', 196),
('RA010', 'Cannot complete rating request for consignee country. Please contact your technical service representative.                                                                      ', 'Cannot complete rating request for consignee country. Please contact your technical service representative.                                                                      ', 197),
('RA011', 'Cannot complete rating request for consignee country. Please contact your technical service representative.                                                                      ', 'Cannot complete rating request for consignee country. Please contact your technical service representative.                                                                      ', 198),
('RA012', 'Package weight exceeds limits for consignee country. Please contact your customer service representative.                                                                        ', 'Package weight exceeds limits for consignee country. Please contact your customer service representative.                                                                        ', 199),
('RA013', 'Total shipment weight exceeds limits for consignee country. Please contact your customer service representative.                                                                 ', 'Total shipment weight exceeds limits for consignee country. Please contact your customer service representative.                                                                 ', 200),
('RA014', 'Warning Note! Dimensions or weights may require special handling or add to transit time. Please contact your customer service representative.                                    ', 'Warning Note! Dimensions or weights may require special handling or add to transit time. Please contact your customer service representative.', 201),
('RA015', 'Shipment not accepted for Transport Collect. Shipping charges not determined. Please contact your customer service representative.                                               ', 'Shipment not accepted for Transport Collect. Shipping charges not determined. Please contact your customer service representative.  ', 202),
('RA016', 'A system service is unavailable. Please resubmit your request at a later time.                                                                                                   ', 'A system service is unavailable. Please resubmit your request at a later time.                                                                                                   ', 203),
('RA017', 'TDD/Jumbo/Jumbo Junior products should not be used in conjunction with 95/96 account numbers                                                                                     ', 'TDD/Jumbo/Jumbo Junior products should not be used in conjunction with 95/96 account numbers                                                                                     ', 204),
('RA018', 'System failure. Please contact your technical service representative.                                                                                                            ', 'Backend unavailable', 205),
('RA019', 'Invalid sector indicator.                                                                         ', 'Invalid sector indicator.                                                                         ', 206),
('RA020', 'Your account is not valid or is not appropriate for this usage.                                   ', 'Invalid Account Number.', 207),
('RA021', 'Invalid local or global product code.                                                             ', 'Local or Global Product is incorrect.Please refer the ReferenceData provided or call our DHL representative.', 208),
('RA022', 'Invalid weight or weight decimals.                                                                ', 'Invalid weight or weight decimals.                                                                ', 209),
('RA023', 'Invalid insurance value or insurance decimals.                                                    ', 'Invalid insurance value or insurance decimals.                                                    ', 210),
('RA024', 'Invalid currency code.                                                                            ', 'Invalid currency code.                                                                            ', 211),
('RA025', 'Invalid Special Service Charge Code.                                                              ', 'Invalid Special Service Charge Code. Please refer to the ReferenceData provided or call our DHL representative.                                                     ', 212),
('RA026', 'Floating sur-charges not allowed for sector.                                                      ', 'Floating sur-charges not allowed for sector.                                                      ', 213),
('RA027', 'Sector do not have min. insurance, charges not computed.                                          ', 'Sector do not have min. insurance, charges not computed.                                          ', 214),
('RA028', 'Insurance is not configured at system parameter.                                                  ', 'Insurance is not configured at system parameter.                                                  ', 215),
('RA029', 'Account/contract/product insurance setup(s) not found.                                            ', 'Account/contract/product insurance setup(s) not found.                                            ', 216),
('RA030', 'Product surcharge is not allowed.                                                                 ', 'Product surcharge is not allowed.                                                                 ', 217),
('RA031', 'No product surcharge configured at account / system.                                              ', 'No product surcharge configured at account / system.                                              ', 218),
('RA032', 'Rate cannot be determined for this combination of product code, origin location and destination.  ', 'Rate cannot be determined for this combination of product code, origin location and destination.  ', 219),
('RA033', 'Insurance currency is invalid for sector.                                                         ', 'Insurance currency is invalid for sector.                                                         ', 220),
('RA034', 'The system was unable to estimate charges for your shipment.                                      ', 'The system was unable to estimate charges for your shipment.                                      ', 221),
('RA035', 'Weight sur-charges not allowed for sector.                                                        ', 'Weight sur-charges not allowed for sector.                                                        ', 222),
('RA036', 'Zip code format not present for the country.                                                      ', 'Zip code format not present for the country.                                                      ', 223),
('RA037', 'No floating surcharge configured.                                                                 ', 'No floating surcharge configured.                                                                 ', 224),
('RA038', 'No weight surcharge configured.                                                                   ', 'No weight surcharge configured.                                                                   ', 225),
('RA039', 'Your account is not valid or is not appropriate for this usage.                                   ', 'Your account is not valid or is not appropriate for this usage.                                   ', 226),
('PU003', 'Cannot schedule a pickup due to unknown city or Zip/postal code. Please contact your technical service representative.    ', 'Cannot schedule a pickup due to unknown city or Zip/postal code. Please contact your technical service representative.    ', 227),
('PU004', 'Account number not valid for pickup.                                                                                      ', 'Account number not valid for pickup.                                                                                      ', 228),
('PU005', 'Unable to verify account number                                                                                           ', 'The system could not verify your account number.', 229),
('PU006', 'Unable to verify account number. To schedule a pickup call customer service representative                                ', 'The system could not verify your account number.Please call the customer service representative                                ', 230),
('PU007a', 'Pickup NOT scheduled due to credit status of account number.                                                                                                                                                                                                   ', 'A pickup was NOT scheduled due to the credit status of account.', 231),
('PU007b', 'Pickup NOT scheduled due to credit status of account number.                                                                                                                                                                                                   ', 'A pickup was NOT scheduled due to the credit status of account.', 232),
('PU008a', 'Pickup NOT scheduled.  Date for pickup has passed. Correct pickup date and resubmit pickup request.                                                                                                                                                            ', 'A pickup was NOT scheduled. Your  date has already passed. Please resubmit your pickup request with a later delivery date.', 233),
('PU008b', 'Pickup NOT scheduled.  Pickup date is more than ten days in advance of current date. Correct pickup date and resubmit.                                                                                                                                         ', 'Pickups cannot be scheduled more than ten days in the future. Please resubmit your pickup request with an earlier delivery date.', 234),
('PU009', 'The requested pickup date is a <?cndtn>. Call customer service.                                                                                                                                                                                                ', 'The requested pickup date is a <?cndtn>. Call customer service.                                                                                                                                                                                                ', 235),
('PU009a', 'Pickup NOT scheduled. There is no weekend pickup service at the location. Please contact your customer service representative.                                                                                                                                 ', 'Pickup NOT scheduled. There is no weekend pickup service at the location. Please contact your customer service representative.                                                                                                                                 ', 236);
INSERT INTO `dhl_error_code` (`error_cde`, `message`, `error_desc`, `id`) VALUES
('PU009b', 'Pickup NOT scheduled. Your ready-by time is not within the Station pickup time range. Please contact your customer service representative.                                                                                                                     ', 'Pickup NOT scheduled. Your ready-by time is not within the Station pickup time range. Please contact your customer service representative.                                                                                                                     ', 237),
('PU009c', 'Pickup NOT scheduled. Pickup date is a holiday. Please reschedule your pickup request date.                                                                                                                                                                    ', 'Pickup NOT scheduled. Pickup date is a holiday. Please reschedule your pickup request date.                                                                                                                                                                    ', 238),
('PU010a', 'Pickup NOT scheduled.  No pickup information for the Zip/postal code. For assistance call technical service representative.                                                                                                                                    ', 'Pickup NOT scheduled.  No pickup information for the Zip/postal code. For assistance call technical service representative.                                                                                                                                    ', 239),
('PU010b', 'Pickup NOT scheduled.  Cannot match Zip/postal code with cutoff times for city For assistance call technical service representative.                                                                                                                           ', 'Pickup NOT scheduled.  Cannot match Zip/postal code with cutoff times for city For assistance call technical service representative.                                                                                                                           ', 240),
('PU011a', 'Pickup NOT scheduled. Insufficient time for the pickup. Please reschedule your pickup request to the next day.                                                                                                                                                 ', 'Pickup NOT scheduled. Insufficient time for the pickup. Please reschedule your pickup request to the next day.                                                                                                                                                 ', 241),
('PU011b', 'Pickup NOT scheduled.  Advance notice for pickup needed at this location. For pickup information call customer service representative.                                                                                                                         ', 'Pickup NOT scheduled.  Advance notice for pickup needed at this location. For pickup information call customer service representative.                                                                                                                         ', 242),
('PU012', 'Pickup NOT scheduled.  Ready by time is passed the station cutoff time. For pickup assistance call customer service representative.                                                                                                                            ', 'Pickup NOT scheduled.  Ready by time is passed the station cutoff time. For pickup assistance call customer service representative.                                                                                                                            ', 243),
('PU013a', 'Pickup NOT scheduled. Ready Time must be earlier than or same as the closing time.                                                                                                                                                                             ', 'Pickup NOT scheduled. Ready Time must be earlier than or same as the closing time.                                                                                                                                                                             ', 244),
('PU013b', 'Pickup NOT scheduled. Pickup request must be at least 1 hr before closing time.                                                                                                                                                                                ', 'Pickup NOT scheduled. Pickup request must be at least 1 hr before closing time.                                                                                                                                                                                ', 245),
('PU013c', 'Ready Time must be greater than Current Time.                                                                                                                                                                                                                  ', 'Ready Time must be greater than Current Time.                                                                                                                                                                                                                  ', 246),
('PU014', 'Shipment(s) exceed normal weight or size limits. If special arrangements are required DHL will telephone the contact person you specified.                                                                                                                     ', 'Shipment(s) exceed normal weight or size limits. If special arrangements are required DHL will telephone the contact person you specified.                                                                                                                     ', 247),
('PU015', 'Pickup NOT scheduled.  Cannot process due to credit status of account. For pickup assistance call customer service representative.                                                                                                                             ', 'Pickup NOT scheduled.  Cannot process due to credit status of account. For pickup assistance call customer service representative.                                                                                                                             ', 248),
('PU016', 'Pickup NOT scheduled.  Pickup location outside the continental United States. For pickup assistance call customer service representative.                                                                                                                      ', 'Pickup NOT scheduled.  Pickup location outside the continental United States. For pickup assistance call customer service representative.                                                                                                                      ', 249),
('PU017a', 'Pickup NOT scheduled.  Registration information missing or invalid. For pickup assistance call technical service representative.                                                                                                                               ', 'Pickup NOT scheduled.  Registration information missing or invalid. For pickup assistance call technical service representative.                                                                                                                               ', 250),
('PU017b', 'Pickup NOT scheduled.  Unable to process your pickup transactions. For pickup assistance call technical service representative.                                                                                                                                ', 'Pickup NOT scheduled.  Unable to process your pickup transactions. For pickup assistance call technical service representative.                                                                                                                                ', 251),
('PU018', 'Pickup service not available at this time. Please try again at later time. If this problem reoccurs contact your technical service representative.                                                                                                             ', 'Pickup service not available at this time. Please try again at later time. If this problem reoccurs contact your technical service representative.                                                                                                             ', 252),
('PU019', 'Pickup NOT scheduled.  Cannot book pickup for account. For pickup assistance call customer service representative.                                                                                                                                             ', 'Pickup NOT scheduled.  Cannot book pickup for account. For pickup assistance call customer service representative.                                                                                                                                             ', 253),
('PU020a', 'Pickup NOT scheduled.  Cannot book a pickup for account. For pickup assistance call customer service representative.                                                                                                                                           ', 'Pickup NOT scheduled.  Cannot book a pickup for account. For pickup assistance call customer service representative.                                                                                                                                           ', 254),
('PU020b', 'Pickup NOT Scheduled.  Cannot book a pickup for account. For pickup assistance call customer service representative.                                                                                                                                           ', 'Pickup NOT Scheduled.  Cannot book a pickup for account. For pickup assistance call customer service representative.                                                                                                                                           ', 255),
('PU021', 'NOTICE!  Packages picked up after hours may be inspected by a DHL Courier for FAA security purposes.                                                                                                                                                           ', 'NOTICE!  Packages picked up after hours may be inspected by a DHL Courier for FAA security purposes.                                                                                                                                                           ', 256),
('PU022', 'Pickup cannot be modified, please contact Customer service Representatives.                                                                                                                                                                                    ', 'Pickup cannot be modified, please contact Customer service Representatives.                                                                                                                                                                                    ', 257),
('PU023', '[PU023] Service Name could not be resolved for given Station. Please contact your customer service representative.', 'Pickup service is not available for the station.', 258),
('PU100', 'Pickup NOT modified.  Cannot verify original pickup information. Please contact your customer service representative.', 'Pickup NOT modified.  Cannot verify original pickup information. Please contact your customer service representative.                                                                                                                                          ', 259),
('PU100a', 'Pickup NOT modified. Cannot process modification now. Please try again at later time. If this problem reoccurs contact your customer service.', 'Pickup NOT modified. Cannot process modification now. Please try again at later time. If this problem reoccurs contact your customer service.                                                                                                                  ', 260),
('PU101', 'Pickup NOT modified. Your pickup request has already been completed. Please contact your customer service representative.', 'Pickup NOT modified. Your pickup request has already been completed. Please contact your customer service representative.                                                                                                                                      ', 261),
('PU102a', 'Unable to modify pickup request! The original request was previously cancelled', 'Unable to modify pickup request! The original request was previously cancelled                                                                                                                                                                                 ', 262),
('PU102b', 'Unable to modify pickup request! This pickup was modified previously. To modify pickup manually call customer service representative. ', 'Unable to modify pickup request! This pickup was modified previously. To modify pickup manually call customer service representative.                                                                                                                          ', 263),
('PU102c', 'Pickup NOT modified!  Pickup has a pending or expired status and cannot be modified. For further information call customer service representative. ', 'Pickup NOT modified!  Pickup has a pending or expired status and cannot be modified. For further information call customer service representative.                                                                                                             ', 264),
('PU103', 'This pickup NOT modified!  The original pickup request was booked outside the pickup service. To modify this pickup call customer service representative. ', 'This pickup NOT modified!  The original pickup request was booked outside the pickup service. To modify this pickup call customer service representative.                                                                                                      ', 265),
('PU104', 'Pickup request NOT modified. Original pickup information cannot be verified. For pickup assistance call customer service representative.', 'Pickup request NOT modified. Original pickup information cannot be verified. For pickup assistance call customer service representative.                                                                                                                       ', 266),
('PU105', 'Pickup request modified successfully. New confirmation number assigned.', 'Pickup request modified successfully. New confirmation number assigned.                                                                                                                                                                                        ', 267),
('PU106', 'Pickup NOT modified.  Missing or invalid information modification request. To modify pickup call technical service representative.', 'ickup NOT modified.  Missing or invalid information modification request. To modify pickup call technical service representative.                                                                                                                              ', 268),
('PU200', 'Pickup NOT cancelled.  Cannot verify original pickup information. Please contact your customer service representative.', 'ickup NOT cancelled.  Cannot verify original pickup information. Please contact your customer service representative.                                                                                                                                          ', 269),
('PU200a', 'Pickup NOT cancelled. Cannot process cancellation now. Please try again at later time. If this problem reoccurs contact your customer service.', 'Pickup NOT cancelled. Cannot process cancellation now. Please try again at later time. If this problem reoccurs contact your customer service.                                                                                                                 ', 270),
('PU201', 'Pickup NOT cancelled.  Pickup information not matched. To cancel the pickup call your customer service representative.', 'Pickup NOT cancelled.  Pickup information not matched. To cancel the pickup call your customer service representative.                                                                                                                                         ', 271),
('PU202', 'Pickup NOT cancelled. Your pickup request has already been completed. Please contact your customer service representative.', 'Pickup NOT cancelled. Your pickup request has already been completed. Please contact your customer service representative.                                                                                                                                     ', 272),
('PU203a', 'The pickup request was previously cancelled. No action required.', 'The pickup request was previously cancelled. No action required.                                                                                                                                                                                               ', 273),
('PU203b', 'Unable to cancel the pickup. Pickup status now pending.', 'Unable to cancel the pickup. Pickup status now pending.                                                                                                                                                                                                        ', 274),
('PU204', 'Unable to cancel this pickup. Not a system scheduled pickup.', 'Unable to cancel this pickup. Not a system scheduled pickup.                                                                      ', 275),
('PU205a', 'Unable to cancel the pickup. System information mismatched. To cancel pickup call your customer service representative.', 'Unable to cancel the pickup. System information mismatched. to cancel pickup call your customer service representative.', 276),
('PU205b', 'Pickup NOT cancelled.  Pickup cannot be cancelled by pickup service. To cancel pickup call your customer service representative.', 'pickup NOT cancelled.  pickup cannot be cancelled by pickup service. to cancel pickup call your customer service representative.', 277),
('PU300', 'System error! System cannot schedule pickups. Please contact your technical service representative.                               ', 'System error! System cannot schedule pickups. Please contact your technical service representative.                               ', 278),
('PU301', 'System error! Cannot schedule pickups. Please contact your technical service representative.                                      ', 'System error! Cannot schedule pickups. Please contact your technical service representative.                                      ', 279),
('PU302', 'System error! Cannot schedule pickups. To schedule a pickup call technical service representative.                                ', 'System error! Cannot schedule pickups. To schedule a pickup call technical service representative.                                ', 280),
('PU303', 'Pickup service not available. Please resubmit your request at later time or contact your technical service representative.        ', 'Pickup service not available. Please resubmit your request at later time or contact your technical service representative.        ', 281),
('PU304', 'We are unable to service this ZIP code. Please contact your DHL sales representative for further assistance', 'The zip code is not supported for pickup.', 282),
('PU306', '[PU306] You have scheduled a pickup outside of business hours.  Please adjust your ready by time.', 'Ready by time is outside the business hours.', 283),
('PU307', '[PU307]Your pickup was NOT scheduled. Packages must be ready at least one hour prior to closing for businesses and two hours prior for residences.', 'Ready by time must be at least one hour prior to closing for business and two hour for residences.', 284),
('PU308', '[PU308]Your pickup was NOT scheduled as it is currently too close to your closing time.  Please change your pickup time or date and resubmit.', 'Pickup time is too close to the closing time. ', 285),
('100000', 'Service operation execution finished succesfully', 'Service operation execution finished succesfully', 286),
('100101', 'Service operation execution faillure', 'Service operation execution faillure', 287),
('202003', 'The input message has invalid Account Number', 'The account number required to be in maximum length of 9 alphanumeric', 288),
('202024', 'The input message has invalid Dest Service Area', 'The input message has invalid Dest Service Area', 289),
('202025', 'The input message has invalid Dest Facility', 'The input message has invalid Dest Facility', 290),
('202048', 'The input message has invalid Facility', 'The input message has invalid Facility', 291),
('202062', 'There are not enough characters in Contact Person', 'Minimum length of contact person is 2.', 292),
('201218', 'The input message has missing Pay Country', 'The input message has missing Pay Country', 293),
('201045', 'The input message has missing Pickup Date', 'The input message has missing Pickup Date', 294),
('201049', 'The input message has missing company name', 'The input message has missing company name', 295),
('201050', 'The input message has missing Telephone', 'The input message has missing Telephone', 296),
('201055', 'The input message has missing application name', 'The input message has missing application name', 297),
('201056', 'The input message has missing pickup service area', 'The input message has missing pickup service area', 298),
('201067', 'The input message has missing address', 'The input message has missing address', 299),
('201071', 'The input message has missing ready time', 'The input message has missing ready time', 300),
('202023', 'The input message has invalid local product code', 'The input message has invalid local product code', 301),
('202064', 'The input message has invalid Pickup Type', 'The input message has invalid Pickup Type', 302),
('201110', 'The input message has missing delivery address', 'The input message has missing delivery address', 303),
('201111', 'The input message has missing delivery telephone number', 'The input message has missing delivery telephone number', 304),
('201112', 'The input message has missing delivery company name', 'The input message has missing delivery company name', 305),
('201113', 'The input message has missing delivery contact person name', 'The input message has missing delivery contact person name', 306),
('201114', 'The input message has missing delivery country code', 'The input message has missing delivery country code', 307),
('201115', 'The input message has missing destination Service Area', 'The input message has missing destination Service Area', 308),
('202110', 'Close Time must be later than ready time', 'Close Time must be later than ready time', 309),
('202113', 'Phone Number Length below Minimum Supported Length', 'Phone Number Length below Minimum Supported Length', 310),
('202114', 'Pickup date is a holiday for country XX', 'Pickup date is a holiday for country XX', 311),
('202115', 'Ready time cannot be greater than close time', 'Ready time cannot be greater than close time', 312),
('202118', 'The input message has invalid piece type', 'The input message has invalid piece type', 313),
('202121', 'The input message has invalid weight/length unit', 'The input message has invalid weight/length unit', 314),
('202122', 'The difference between ready time and close time must be at least XX minutes', 'The difference between ready time and close time must be at least XX minutes', 315),
('202123', 'Account payment is not allowed for stopped credit customer', 'Account payment is not allowed for stopped credit customer', 316),
('202124', 'Remote Booking can only be made by IMP Account', 'Remote Booking can only be made by IMP Account', 317),
('201204', 'The input message has missing close time', 'The input message has missing close time', 318),
('201206', 'The input message has missing payer account number', 'The input message has missing payer account number', 319),
('201210', 'The input message has missing requestor address', 'The input message has missing requestor address', 320),
('201211', 'The input message has missing requestor city', 'The input message has missing requestor city', 321),
('201212', 'The input message has missing requestor company name', 'The input message has missing requestor company name', 322),
('201213', 'The input message has missing requestor contact person name', 'The input message has missing requestor contact person name', 323),
('201216', 'The input message has missing requestor telephone number', 'The input message has missing requestor telephone number', 324),
('202128', 'The Pickup date is earlier than the current date', 'The Pickup date is earlier than the current date', 325),
('202401', 'No billing address found', 'No billing address found', 326),
('207901', 'An unexpected exception has occurred in BookingServices', 'An unexpected exception has occurred in BookingServices', 327),
('201001', 'The input message has missing Account Type', 'The input message has missing Account Type', 328),
('202001', 'The input message has invalid Account Type', 'The input message has invalid Account Type', 329),
('202129', 'The input message has invalid delivery country code', 'Invalid receiver country code.', 330),
('202131', 'Account payment is not allowed for cut credit customer', 'Account number is in bad credit status is not allowed.', 331),
('RT1001', 'The service area is suspended or not in action.                                ', 'The service area is suspended or not in action.                                ', 332),
('RT1002', 'The service area is unavailable.                                               ', 'The service area is unavailable.                                               ', 333),
('RT1003', 'The service area is not opened.                                                ', 'The service area is not opened.                                                ', 334),
('RT1004', 'The service area is closed.                                                    ', 'The service area is closed.                                                    ', 335),
('RT1005', 'The status of the service area is unknown.                                     ', 'The status of the service area is unknown.                                     ', 336),
('RT1006', 'The search for the service area information has failed                         ', 'The search for the service area information has failed                         ', 337),
('RT1101', 'The postal code is not provided by the user.                                   ', 'The postal code is not provided by the user.                                   ', 338),
('RT1102', 'The postal code provided by user is invalid.                                   ', 'The postal code provided by user is invalid.                                   ', 339),
('RT1103', 'The postal code provided by user does not exist in the country.                ', 'The postal code provided by user does not exist in the country.                ', 340),
('RT1104', 'The city name provided by user does not exist in the country.                  ', 'The city name provided by user does not exist in the country.                  ', 341),
('RT1105', 'More than one city with the same name found.                                   ', 'More than one city with the same name found.                                   ', 342),
('RT1106', 'More than one service areas are found in the city.                             ', 'More than one service areas are found in the city.                             ', 343),
('RT1107', 'Multiple Cities found for the same postal code.                                ', 'Multiple Cities found for the same postal code.                                ', 344),
('RT1108', 'The city name provided by the user does not have an exact match                ', 'The city name provided by the user does not have an exact match                ', 345),
('RT1109', 'The postal code is incorrectly written in the city or the division field.      ', 'The postal code is incorrectly written in the city or the division field.      ', 346),
('RT1110', 'The postal code is incorrectly written in the address field.                   ', 'The postal code is incorrectly written in the address field.                   ', 347),
('440000', 'Unexpected DCT error description', 'Unexpected error description.', 348),
('320001', 'XML validation error: <technical error messages generated by xml  framework>', 'XML validation failed.', 349),
('320002', 'The format of the ready time is not correct. Please check the time format.', 'Incorrect time format.', 350),
('340001', 'The origin country code ${FromCountryCode} could not be found. Please check the country code.', 'Origin Country Code not found.', 351),
('340002', 'The destination country code ${ToCountryCode} could not be found. Please check the country code.', 'Destination Country Code not found.', 352),
('340003', 'The payment country code ${PaymentCountryCode} could not be found.', 'Payment Country Code not found.', 353),
('340004', 'The location information is missing. At least one attribute post code, city name or suburb name should be provided', 'Location information is not complete. Please specify at least post code, city name or suburb name.', 354),
('340005', 'The pickup date ${Date} is missing. The pickup date is a mandatory field.', 'Pick up date is missing. ', 355),
('340006', 'The ready time ${ReadyTime} is missing. This is a mandatory parameter.', 'Ready time is missing.', 356),
('340007', 'The commodity code could not be found, please check the commodity code.', 'Commodity code not found.', 357),
('340008', 'The piece weight ${PiecesPieceWeight} is missing. This is mandatory information.', 'Piece Weight is missing.', 358),
('340009', 'The number of pieces is missing.', 'Please enter number of pieces.', 359),
('340010', 'The total shipment volume is missing.', 'Please enter total shipment volume is missing. ', 360),
('340011', 'The maximum piece weight is missing.', 'Please enter maximum piece weight.', 361),
('340012', 'The maximum piece height is missing.', 'Please enter maximum piece height.', 362),
('340013', 'The maximum piece length is missing.', 'Please enter maximum piece length.', 363),
('340014', 'The maximum piece width/diameter is missing.', 'Please enter maximum piece width/diameter.', 364),
('340015', 'The declared value is missing.', 'Please enter declared value.', 365),
('340016', 'The piece type is invalid.', 'Please enter piece type.', 366),
('340017', 'The unit of weight is missing.', 'Please enter unit of weight.', 367),
('340018', 'The declared value ${DeclaredValue} cannot exceed the limit set for the country.', 'Declared value must be within the limit set for the country.', 368),
('340019', 'Unknown unit of measure for weight ${WeightUnit}.', 'Please provide a valid unit of measure for weight.', 369),
('340020', 'Unknown unit of measure for dimensions ${DimensionUnit}.', 'Please provide a valid unit of measure for dimensions.', 370),
('340021', 'The currency is missing.', 'Please enter the currency.', 371),
('340022', 'The maximum piece weight is greater than the total shipment weight ${ShipmentWeight}.', 'The maximum piece weight is greater than the total shipment weight. ', 372),
('340023', 'Currency symbol ${CurrencyCode} or ${DeclaredCurrency} or ${InsuredCurrency} could not be found. Please check the currency symbol field.', 'Please check the currency symbol field. ', 373),
('340024', 'The Global Product Code ${GlobalProductCode} or Local Product Code ${LocalProductCode} information is/are missing.', 'The Global or Local Product Code is required.', 374),
('340025', 'The Global Service Code ${GlobalServiceCode} or Local Service Code ${LocalServiceCode} information is/are missing.', 'The Global or Local Service Code is required.', 375),
('340026', 'Invalid combinations of unit of measurement for weight ${WeightUnit} and unit of measurement for dimension ${DimensionUnit}. Please check units of weight and dimension value.', 'Please check units of weight and dimension value.', 376),
('340027', 'Invalid Global Product Code ${QtdShpGlobalProductCode} and Special Service Type ${QtdShpQtdShpExChrgSpecialServiceType} combination. Please check the product and service combination.', 'Please check the product and service combination.', 377),
('340028', 'The unit of measure is missing.', 'Please enter the unit of measure.', 378),
('340029', 'UOM should be same for all dimensions', 'UOM should be same for all dimensions.', 379),
('340030', 'Unknown Generic Criteria code', 'Please enter a valid Generic Criteria Code.', 380),
('340031', 'The format of the dimensions is not correct. Please check the dimensions format.', 'Please check the dimensions format.', 381),
('340032', 'The format of the weight is not correct. Please check the weight format.', 'Please check the weight format.', 382),
('340033', 'Invalid ready time format', 'Please enter the Ready Time in correct format.', 383),
('340035', 'The unit of dimension is missing', 'Please enter the Unit of Dimension.', 384),
('420501', 'The origin country code ${FromCountryCode} could not be found. Please check the country code.', 'Please check the origin country code.', 385),
('420502', 'The destination country code ${ToCountryCode} could not be found. Please check the country code.', 'Please check the destination country code.', 386),
('420503', 'The payment country code ${PaymentCountryCode} could not be found.', 'Please check the Payment Country Code.', 387),
('420504', 'The origin location is invalid. Please check the data.', 'Please check the Origin Location.', 388),
('420505', 'The destination location is invalid. Please check the data.', 'Please check the destination location.', 389),
('420506', 'Postcode not found. Expected formats: <country specific post code format>', 'Please enter the Postcode in correct format.', 390),
('520101', 'DCT PE configuration error', 'DCT Pricing Engine configuration error.', 391),
('520102', 'PE timeout', 'Pricing Engine timeout', 392),
('520103', 'Account specific PE error', 'Account specific Pricing Engine error', 393),
('520104', 'Weight specific PE error ', 'Weight specific Pricing Engine error ', 394),
('520201', 'Error code from PE response +  Error text propagated from PE response', 'Error code from Pricing Engine response +  Error text propagated from Pricing Engine response', 395),
('510101', 'Warning code from PE response +  Warning text propagated from PE response', 'Warning code from Pricing Engine response +  Warning text propagated from Pricing Engine response', 396),
('DCT_0001', 'The requested Global Product Code ${GlobalProductCode} and Local Product Code ${LocalProductCode} is not available between this origin and destination. Please make sure data entered is valid before proceeding or contact our customer service.', 'The requested product(s) not available based on your search criteria.', 397),
('DCT_0002', 'The requested Special Service Codes ${SpecialServiceCode} is not available. Please make sure data entered is valid before proceeding or contact our customer service.', 'The requested services(s) not available based on your search criteria.', 398),
('410501', 'Pickup PL ambiguity rule applied. More than 1 PL is available for the given PL attributes.', 'More than one Postal Location is available for the given Postal Location attributes.', 399),
('410502', 'Pickup PL fallback rule applied : PS->CP', 'Pickup Postal Location fallback rule applied : Postcode Suburb->City Postcode', 400),
('410503', 'Pickup PL fallback rule applied : PS->CP->P ', 'Pickup Postal Location fallback rule applied : Postcode Suburb->City Postcode->Postcode', 401),
('410504', 'Pickup PL fallback rule applied : PS->CP->P->C ', 'Pickup Postal Location fallback rule applied : Postcode Suburb->City Postcode->Postcode->City ', 402),
('410505', 'Pickup PL fallback rule applied : CP->P', 'Pickup Postal Location fallback rule applied : City Postcode->Postcode', 403),
('410506', 'Pickup PL fallback rule applied : CP->P->C', 'Pickup Postal Location fallback rule applied : City Postcode->Postcode->City', 404),
('410507', 'Pickup PL fallback rule applied : P->C', 'Pickup Postal Location fallback rule applied : Postcode->City', 405),
('410508', 'Pickup PL fallback rule applied : S->C', 'Pickup Postal Location fallback rule applied : Suburb->City', 406),
('410509', 'Delivery  PL ambiguity rule applied. More than 1 PL is available for the given PL attributes.', 'Delivery  Postal Location ambiguity rule applied. More than 1 Postal Location  is available for the given PL attributes.', 407),
('410510', 'Delivery PL fallback rule applied : PS->CP', 'Delivery Postal Location fallback rule applied : Postcode Suburb->City Postcode', 408),
('410511', 'Delivery PL fallback rule applied : PS->CP->P ', 'Delivery Postal Location fallback rule applied : Postcode Suburb->City Postcode->Postcode', 409),
('410512', 'Delivery PL fallback rule applied : PS->CP->P->C ', 'Delivery Postal Location fallback rule applied : Postcode Suburb->City Postcode->Postcode->City ', 410),
('410513', 'Delivery PL fallback rule applied : CP->P', 'Delivery Postal Location fallback rule applied : City Postcode->Postcode', 411),
('410514', 'Delivery PL fallback rule applied : CP->P->C', 'Delivery Postal Location fallback rule applied : City Postcode->Postcode->City', 412),
('410515', 'Delivery PL fallback rule applied : P->C', 'Delivery Postal Location fallback rule applied : Postcode->City', 413),
('410517', 'The origin facility is suspended.', 'The origin facility is suspended.', 414),
('410518', 'The destination facility is suspended.', 'The destination facility is suspended.', 415),
('410201', 'Pick-up service is not provided on this day. ', 'Pick-up service is not provided on this day. ', 416),
('410202', 'The pickup date is outside of sliding window: dateFrom-dateTo', 'The pickup date is outside of sliding window: dateFrom-dateTo', 417),
('410203', 'Ready time is outside of pickup window', 'Ready time is outside of pickup window', 418),
('410301', 'Product not available between this origin and destination (network segment).', 'Product not available between this origin and destination (network segment).', 419),
('410302', 'Temporary network target change', 'Temporary network target change', 420),
('410303', 'Avaliable products removed by Marketed filtering', 'Avaliable products removed by Marketed filtering', 421),
('410401', 'Location does not provide delivery', 'Location does not provide delivery', 422),
('410402', 'Delivery date is outside of sliding window', 'Delivery date is outside of sliding window', 423),
('410101', 'The shipment weight exceeds max', 'The shipment weight exceeds maximum limits', 424),
('410102', 'The shipment height exceeds max', 'The shipment height exceeds maximum limits', 425),
('410103', 'The shipment length exceeds max', 'The shipment length exceeds maximum limits', 426),
('410104', 'The shipment width/diameter exceeds max', 'The shipment width/diameter exceeds maximum liminted', 427),
('410105', 'The requested product(s) not available based on your search criteria.Dropped products global/local: |?', 'The requested product(s) not available based on your search criteria.Dropped products global/local: |?', 428),
('410106', 'The piece weight exceeds max', 'The piece weight exceeds maximum limits', 429),
('410107', 'The piece height exceeds max', 'The piece height exceeds maximum limits', 430),
('410108', 'The piece length exceeds max', 'The piece length exceeds maximum limits', 431),
('410109', 'The piece width/diameter exceeds max', 'The piece width/diameter exceeds maximum limits', 432),
('410110', 'The shipment weight exceeds max', 'The shipment weight exceeds maximum limits', 433),
('410111', 'The shipment height exceeds max', 'The shipment height exceeds maximum limits', 434),
('410112', 'The shipment length is not within the restrictions', 'The shipment length is not within the restrictions', 435),
('410113', 'The shipment width/diameter under min', 'The shipment width/diameter under min', 436),
('410114', 'The min piece dimension not reached', 'The min piece dimension not reached', 437),
('410115', 'The mid piece dimension not reached', 'The mid piece dimension not reached', 438),
('410116', 'The max piece dimension not reached', 'The max piece dimension not reached', 439),
('410117', 'The minimum piece weight not met', 'The minimum piece weight not met', 440),
('410118', 'Number of pieces exceeded', 'Number of pieces exceeded', 441),
('410119', 'The min shipment dimension not reached', 'The min shipment dimension not reached', 442),
('410120', 'The mid shipment dimension not reached', 'The mid shipment dimension not reached', 443),
('410121', 'The max shipment dimension not reached', 'The max shipment dimension not reached', 444),
('410122', 'The minimum shipment weight not met', 'The minimum shipment weight not met', 445),
('410123', 'The max shipment declared value exceeded', 'The max shipment declared value exceeded', 446),
('410124', 'Geographical market rule applied', 'Geographical market rule applied', 447),
('410125', 'Minimal inbound currency value not met', 'Minimal inbound currency value not met', 448),
('410126', 'Maximum inbound currency value exceeded', 'Maximum inbound currency value exceeded', 449),
('410127', 'Minimum number of pieces not met', 'Minimum number of pieces not met', 450),
('410128', 'Minimal outbound currency value not met', 'Minimal outbound currency value not met', 451),
('410129', 'Maximum outbound currency value exceeds', 'Maximum outbound currency value exceeds', 452),
('410130', 'Minimal number of pallet not met', 'Minimal number of pallet not met', 453),
('410131', 'Maximum number of pallet exceeds', 'Maximum number of pallet exceeds', 454),
('410132', 'Minimal pallet weight not met', 'Minimal pallet weight not met', 455),
('410133', 'Maximum pallet weight exceeds', 'Maximum pallet weight exceeds', 456),
('410134', 'The max(length; width; height) piece exceeds max', 'The max(length; width; height) piece exceeds max', 457);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `dhl_error_code`
--
ALTER TABLE `dhl_error_code`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `dhl_error_code`
--
ALTER TABLE `dhl_error_code`
  MODIFY `id` int(11) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=458;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
