
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;



-- --------------------------------------------------------

--
-- Table structure for table `dhl_special_services`
--

CREATE TABLE IF NOT EXISTS `dhl_special_services` (
  `prd_cde` char(2) NOT NULL,
  `prd_desc` varchar(30) NOT NULL,
  `prd_group_cde` char(2) DEFAULT NULL,
  `prd_group_desc` varchar(30) NOT NULL,
  `charge_cde` char(3) NOT NULL,
  `charge_desc` varchar(15) NOT NULL,
  `id` int(11) unsigned NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=227 DEFAULT CHARSET=latin1 PACK_KEYS=1;

--
-- Dumping data for table `dhl_special_services`
--

INSERT INTO `dhl_special_services` (`prd_cde`, `prd_desc`, `prd_group_cde`, `prd_group_desc`, `charge_cde`, `charge_desc`, `id`) VALUES
('0A', 'Logistics Services', '0', 'LOGISTICS SERVICES', 'FEE', 'Fees', 2),
('0B', 'Mailroom Management', '1', 'LOGISTICS SERVICES', 'FEE', 'Fees', 3),
('0C', 'Pallet Administration', '2', 'LOGISTICS SERVICES', 'FEE', 'Fees', 4),
('0D', 'Warehousing', '3', 'LOGISTICS SERVICES', 'FEE', 'Fees', 5),
('0E', 'Express Logistics Centre', '4', 'LOGISTICS SERVICES', 'FEE', 'Fees', 6),
('0F', 'Strategic Parts Centre', '5', 'LOGISTICS SERVICES', 'FEE', 'Fees', 7),
('0G', 'Local Distribution Centre', '6', 'LOGISTICS SERVICES', 'FEE', 'Fees', 8),
('0H', 'Terminal Handling', '7', 'LOGISTICS SERVICES', 'FEE', 'Fees', 9),
('0I', 'Cross Docking', '8', 'LOGISTICS SERVICES', 'FEE', 'Fees', 10),
('0J', 'Inventory Management', '9', 'LOGISTICS SERVICES', 'FEE', 'Fees', 11),
('0K', 'Loading/Unloading', '10', 'LOGISTICS SERVICES', 'FEE', 'Fees', 12),
('0L', 'Product Kitting', '11', 'LOGISTICS SERVICES', 'FEE', 'Fees', 13),
('0M', 'Priority Account Desk', '12', 'LOGISTICS SERVICES', 'FEE', 'Fees', 14),
('0N', 'Document Archiving', '13', 'LOGISTICS SERVICES', 'FEE', 'Fees', 15),
('AA', 'Saturday Delivery', 'A', 'NON STANDARD DAY', 'XCH', 'Extra Charges', 16),
('AB', 'Saturday Pickup', 'A', 'NON STANDARD DAY', 'XCH', 'Extra Charges', 17),
('AC', 'Holiday Delivery', 'A', 'NON STANDARD DAY', 'XCH', 'Extra Charges', 18),
('AD', 'Holiday Pickup', 'A', 'NON STANDARD DAY', 'XCH', 'Extra Charges', 19),
('AG', 'Domestic Saturday Delivery', 'A', 'NON STANDARD DAY', 'XCH', 'Extra Charges', 20),
('BA', 'Standard', 'B', 'GLOBALMAIL ITEM', 'INC', 'Included', 21),
('BB', 'Globalmail Item', 'B', 'GLOBALMAIL ITEM', 'SCH', 'Surcharges', 22),
('BC', 'Letter', 'B', 'GLOBALMAIL ITEM', 'SCH', 'Surcharges', 23),
('BD', 'Packet', 'B', 'GLOBALMAIL ITEM', 'SCH', 'Surcharges', 24),
('BE', 'Letter Plus', 'B', 'GLOBALMAIL ITEM', 'SCH', 'Surcharges', 25),
('BF', 'Packet Plus', 'B', 'GLOBALMAIL ITEM', 'SCH', 'Surcharges', 26),
('CA', 'Elevated Risk', 'C', 'SECURITY SERVICES', 'SCH', 'Surcharges', 27),
('CB', 'Restricted Destination', 'C', 'SECURITY SERVICES', 'SCH', 'Surcharges', 28),
('CC', 'Security Validation', 'C', 'SECURITY SERVICES', 'SCH', 'Surcharges', 29),
('CD', 'Secure Protection', 'C', 'SECURITY SERVICES', 'XCH', 'Extra Charges', 30),
('CE', 'Proof of Identity', 'C', 'SECURITY SERVICES', 'XCH', 'Extra Charges', 31),
('CF', 'Secure Storage', 'C', 'SECURITY SERVICES', 'XCH', 'Extra Charges', 32),
('CG', 'Diplomatic Material', 'C', 'SECURITY SERVICES', 'XCH', 'Extra Charges', 33),
('CH', 'Smart Sensor', 'C', 'SECURITY SERVICES', 'XCH', 'Extra Charges', 34),
('CI', 'Visa Program', 'C', 'SECURITY SERVICES', 'XCH', 'Extra Charges', 35),
('CJ', 'Onboard Courier', 'C', 'SECURITY SERVICES', 'XCH', 'Extra Charges', 36),
('CK', 'Secure Safebox', 'C', 'SECURITY SERVICES', 'XCH', 'Extra Charges', 37),
('CL', 'Smart Sentry', 'C', 'SECURITY SERVICES', 'XCH', 'Extra Charges', 38),
('DC', 'Split Duties & Tax', 'D', 'BILLING SERVICES', 'XCH', 'Extra Charges', 39),
('DD', 'Duties & Taxes Paid', 'D', 'BILLING SERVICES', 'XCH', 'Extra Charges', 40),
('DE', 'Receiver Paid', 'D', 'BILLING SERVICES', 'XCH', 'Extra Charges', 41),
('DS', 'Duties & Taxes Unpaid', 'D', 'BILLING SERVICES', 'INC', 'Included', 42),
('DT', 'Import Billing', 'D', 'BILLING SERVICES', 'INC', 'Included', 43),
('DU', 'Importer of Record', 'D', 'BILLING SERVICES', 'INC', 'Included', 44),
('EA', 'GoGreen Carbon Neutral', 'E', 'ENVIRONMENTAL SERVICES', 'XCH', 'Extra Charges', 45),
('EB', 'GoGreen Carbon Footprint', 'E', 'ENVIRONMENTAL SERVICES', 'FEE', 'Fees', 46),
('EC', 'GoGreen Carbon Estimate', 'E', 'ENVIRONMENTAL SERVICES', 'FEE', 'Fees', 47),
('FB', 'Fuel Surcharge', 'F', 'FUEL SURCHARGE', 'SCH', 'Surcharges', 48),
('FC', 'Fuel Surcharge', 'F', 'FUEL SURCHARGE', 'SCH', 'Surcharges', 49),
('FF', 'Fuel Surcharge', 'F', 'FUEL SURCHARGE', 'SCH', 'Surcharges', 50),
('GA', 'Smartphone Box', 'G', 'PACKAGING SERVICES', 'XCH', 'Extra Charges', 51),
('GB', 'Laptop Box', 'G', 'PACKAGING SERVICES', 'XCH', 'Extra Charges', 52),
('GC', 'Bottle Box', 'G', 'PACKAGING SERVICES', 'XCH', 'Extra Charges', 53),
('GD', 'Repacking', 'G', 'PACKAGING SERVICES', 'XCH', 'Extra Charges', 54),
('GE', 'Tablet Box', 'G', 'PACKAGING SERVICES', 'XCH', 'Extra Charges', 55),
('GF', 'Filler Material', 'G', 'PACKAGING SERVICES', 'XCH', 'Extra Charges', 56),
('GG', 'Packaging', 'G', 'PACKAGING SERVICES', 'XCH', 'Extra Charges', 57),
('GH', 'Diplomatic Bag', 'G', 'PACKAGING SERVICES', 'XCH', 'Extra Charges', 58),
('GI', 'Pallet Box', 'G', 'PACKAGING SERVICES', 'XCH', 'Extra Charges', 59),
('GJ', 'Lock Box', 'C', 'SECURITY SERVICES', 'XCH', 'Extra Charges', 60),
('HB', 'Lithium Ion PI965 Section II', 'H', 'NON STANDARD CONTENTS', 'SCH', 'Surcharges', 61),
('HC', 'Dry Ice UN1845', 'H', 'NON STANDARD CONTENTS', 'XCH', 'Extra Charges', 62),
('HD', 'Lithium Ion PI965-966 Section ', 'H', 'NON STANDARD CONTENTS', 'XCH', 'Extra Charges', 63),
('HE', 'Dangerous Goods', 'H', 'NON STANDARD CONTENTS', 'XCH', 'Extra Charges', 64),
('HG', 'Perishable Cargo', 'H', 'NON STANDARD CONTENTS', 'SCH', 'Surcharges', 65),
('HH', 'Excepted Quantity', 'H', 'NON STANDARD CONTENTS', 'XCH', 'Extra Charges', 66),
('HI', 'Spill Cleaning', 'H', 'NON STANDARD CONTENTS', 'SCH', 'Surcharges', 67),
('HK', 'Consumer Commodities', 'H', 'NON STANDARD CONTENTS', 'XCH', 'Extra Charges', 68),
('HL', 'Limited Quantities ADR', 'H', 'NON STANDARD CONTENTS', 'XCH', 'Extra Charges', 69),
('HM', 'Lithium Metal PI969 Section II', 'H', 'NON STANDARD CONTENTS', 'XCH', 'Extra Charges', 70),
('HN', 'ADR Load Exemption', 'H', 'NON STANDARD CONTENTS', 'XCH', 'Extra Charges', 71),
('HV', 'Lithium Ion PI967-Section II', 'H', 'NON STANDARD CONTENTS', 'INC', 'Included', 72),
('HW', 'Lithium Metal PI970-Section II', 'H', 'NON STANDARD CONTENTS', 'INC', 'Included', 73),
('HY', 'Biological UN3373', 'H', 'NON STANDARD CONTENTS', 'INC', 'Included', 74),
('IB', 'Extended Liability', 'I', 'INSURANCE SERVICES', 'XCH', 'Extra Charges', 75),
('IC', 'Contract Insurance', 'I', 'INSURANCE SERVICES', 'FEE', 'Fees', 76),
('II', 'Shipment Insurance', 'I', 'INSURANCE SERVICES', 'XCH', 'Extra Charges', 77),
('JA', 'Delivery Notification', 'J', 'SHIPMENT NOTIFICATION', 'XCH', 'Extra Charges', 78),
('JC', 'Pickup Notification', 'J', 'SHIPMENT NOTIFICATION', 'XCH', 'Extra Charges', 79),
('JD', 'Proactive Tracking', 'J', 'SHIPMENT NOTIFICATION', 'XCH', 'Extra Charges', 80),
('JE', 'Performance Reporting', 'J', 'SHIPMENT NOTIFICATION', 'FEE', 'Fees', 81),
('JY', 'Prealert Notification', 'J', 'SHIPMENT NOTIFICATION', 'INC', 'Included', 82),
('KA', 'Change of Billing', 'K', 'BILLING INSTRUCTIONS', 'FEE', 'Fees', 83),
('KB', 'Cash On Delivery', 'K', 'BILLING INSTRUCTIONS', 'XCH', 'Extra Charges', 84),
('KD', 'Printed Invoice', 'K', 'BILLING INSTRUCTIONS', 'FEE', 'Fees', 85),
('KE', 'Waybill Copy', 'K', 'BILLING INSTRUCTIONS', 'XCH', 'Extra Charges', 86),
('KF', 'Import Paperwork', 'K', 'BILLING INSTRUCTIONS', 'XCH', 'Extra Charges', 87),
('KY', 'Payment on Pickup', 'K', 'BILLING INSTRUCTIONS', 'INC', 'Included', 88),
('LA', 'Shipment Intercept', 'L', 'SHIPMENT INTERCEPT', 'XCH', 'Extra Charges', 89),
('LC', 'Shipment Redirect', 'L', 'SHIPMENT INTERCEPT', 'XCH', 'Extra Charges', 90),
('LE', 'Storage at Facility', 'L', 'SHIPMENT INTERCEPT', 'SCH', 'Surcharges', 91),
('LG', 'Cold Storage', 'L', 'SHIPMENT INTERCEPT', 'XCH', 'Extra Charges', 92),
('LH', 'Specific Routing', 'L', 'SHIPMENT INTERCEPT', 'FEE', 'Fees', 93),
('LV', 'Service Recovery', 'L', 'SHIPMENT INTERCEPT', 'INC', 'Included', 94),
('LW', 'Alternative Address', 'L', 'SHIPMENT INTERCEPT', 'INC', 'Included', 95),
('LX', 'Hold for Collection', 'L', 'SHIPMENT INTERCEPT', 'INC', 'Included', 96),
('MA', 'Address Correction', 'M', 'ADDRESS CORRECTION', 'SCH', 'Surcharges', 97),
('MB', 'Address Correction', 'M', 'ADDRESS CORRECTION', 'SCH', 'Surcharges', 98),
('NN', 'Neutral Delivery', 'D', 'BILLING SERVICES', 'XCH', 'Extra Charges', 99),
('OB', 'Remote Area Pickup', 'O', 'REMOTE AREA SERVICE', 'SCH', 'Surcharges', 100),
('OC', 'Remote Area Delivery', 'O', 'REMOTE AREA SERVICE', 'SCH', 'Surcharges', 101),
('OE', 'Out of Service Area', 'O', 'REMOTE AREA SERVICE', 'SCH', 'Surcharges', 102),
('OO', 'Remote Area Delivery', 'O', 'REMOTE AREA SERVICE', 'SCH', 'Surcharges', 103),
('PA', 'Shipment Preparation', 'P', 'SHIPMENT PREPARATION', 'XCH', 'Extra Charges', 104),
('PB', 'Shipment Labeling', 'P', 'SHIPMENT PREPARATION', 'FEE', 'Fees', 105),
('PC', 'Shipment Consolidation', 'P', 'SHIPMENT PREPARATION', 'XCH', 'Extra Charges', 106),
('PD', 'Relabeling/Data Entry', 'P', 'SHIPMENT PREPARATION', 'SCH', 'Surcharges', 107),
('PE', 'Preprinted Waybill', 'P', 'SHIPMENT PREPARATION', 'FEE', 'Fees', 108),
('PS', 'Piece Labelling', 'P', 'SHIPMENT PREPARATION', 'XCH', 'Extra Charges', 109),
('PT', 'Data Staging 03', 'P', 'SHIPMENT PREPARATION', 'INC', 'Included', 110),
('PU', 'Data Staging 06', 'P', 'SHIPMENT PREPARATION', 'INC', 'Included', 111),
('PV', 'Data Staging 12', 'P', 'SHIPMENT PREPARATION', 'INC', 'Included', 112),
('PW', 'Data Staging 24', 'P', 'SHIPMENT PREPARATION', 'INC', 'Included', 113),
('PX', 'Standard Pickup', 'P', 'SHIPMENT PREPARATION', 'SCH', 'Surcharges', 114),
('PY', 'Scheduled Pickup', 'P', 'SHIPMENT PREPARATION', 'FEE', 'Fees', 115),
('QA', 'Dedicated Pickup', 'Q', 'NON STANDARD PICKUP', 'XCH', 'Extra Charges', 116),
('QB', 'Early Pickup', 'Q', 'NON STANDARD PICKUP', 'XCH', 'Extra Charges', 117),
('QD', 'Late Pickup', 'Q', 'NON STANDARD PICKUP', 'XCH', 'Extra Charges', 118),
('QE', 'Residential Pickup', 'Q', 'NON STANDARD PICKUP', 'SCH', 'Surcharges', 119),
('QF', 'Loading/Waiting', 'Q', 'NON STANDARD PICKUP', 'SCH', 'Surcharges', 120),
('QH', 'Bypass Injection', 'Q', 'NON STANDARD PICKUP', 'INC', 'Included', 121),
('QI', 'Direct Injection', 'Q', 'NON STANDARD PICKUP', 'INC', 'Included', 122),
('QY', 'Drop Off at Facility', 'Q', 'NON STANDARD PICKUP', 'INC', 'Included', 123),
('SA', 'Delivery Signature', 'S', 'SIGNATURE SERVICE', 'XCH', 'Extra Charges', 124),
('SB', 'Content Signature', 'S', 'SIGNATURE SERVICE', 'XCH', 'Extra Charges', 125),
('SC', 'Named Signature', 'S', 'SIGNATURE SERVICE', 'XCH', 'Extra Charges', 126),
('SD', 'Adult Signature', 'S', 'SIGNATURE SERVICE', 'XCH', 'Extra Charges', 127),
('SE', 'Contract Signature', 'S', 'SIGNATURE SERVICE', 'XCH', 'Extra Charges', 128),
('SW', 'Alternative Signature', 'S', 'SIGNATURE SERVICE', 'INC', 'Included', 129),
('SX', 'No Signature Required', 'S', 'SIGNATURE SERVICE', 'INC', 'Included', 130),
('TA', 'Dedicated Delivery', 'T', 'NON STANDARD DELIVERY', 'XCH', 'Extra Charges', 131),
('TB', 'Early Delivery', 'T', 'NON STANDARD DELIVERY', 'INC', 'Included', 132),
('TC', 'Time Window Delivery', 'T', 'NON STANDARD DELIVERY', 'XCH', 'Extra Charges', 133),
('TD', 'Evening Delivery', 'T', 'NON STANDARD DELIVERY', 'XCH', 'Extra Charges', 134),
('TE', 'Delivery on Appointment', 'T', 'NON STANDARD DELIVERY', 'XCH', 'Extra Charges', 135),
('TG', 'Return Undeliverable', 'T', 'NON STANDARD DELIVERY', 'XCH', 'Extra Charges', 136),
('TH', 'Swap Delivery', 'T', 'NON STANDARD DELIVERY', 'XCH', 'Extra Charges', 137),
('TJ', 'Unloading/Waiting', 'T', 'NON STANDARD DELIVERY', 'SCH', 'Surcharges', 138),
('TK', 'Residential Delivery', 'T', 'NON STANDARD DELIVERY', 'SCH', 'Surcharges', 139),
('TN', 'Repeat Delivery', 'T', 'NON STANDARD DELIVERY', 'INC', 'Included', 140),
('TT', 'Alternative Date', 'T', 'NON STANDARD DELIVERY', 'INC', 'Included', 141),
('TU', 'No Partial Delivery', 'T', 'NON STANDARD DELIVERY', 'INC', 'Included', 142),
('TV', 'Service Point 24/7', 'T', 'NON STANDARD DELIVERY', 'INC', 'Included', 143),
('TW', 'Pre 9:00', 'T', 'NON STANDARD DELIVERY', 'INC', 'Included', 144),
('TX', 'Pre 10:30', 'T', 'NON STANDARD DELIVERY', 'INC', 'Included', 145),
('TY', 'Pre 12:00', 'T', 'NON STANDARD DELIVERY', 'INC', 'Included', 146),
('UA', 'Thermo Packaging', 'U', 'PAYMENT DEFERMENT', 'FEE', 'Fees', 147),
('UB', 'Ambient Vialsafe', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 148),
('UC', 'Ambient Non Insulated', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 149),
('UD', 'Ambient Insulated', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 150),
('UE', 'Ambient Extreme', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 151),
('UF', 'Chilled Box S', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 152),
('UG', 'Chilled Box M', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 153),
('UH', 'Chilled Box L', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 154),
('UI', 'Frozen No Ice S', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 155),
('UJ', 'Frozen No Ice M', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 156),
('UK', 'Frozen No Ice L', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 157),
('UL', 'Frozen Ice Sticks S', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 158),
('UM', 'Frozen Ice Sticks M', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 159),
('UN', 'Frozen Ice Sticks L', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 160),
('UO', 'Frozen Ice Plates S', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 161),
('UP', 'Frozen Ice Plates M', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 162),
('UQ', 'Frozen Ice Plates L', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 163),
('UR', 'Combination No Ice', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 164),
('US', 'Combination Dry Ice', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 165),
('UT', 'Frozen Ice Sticks E', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 166),
('UV', 'Frozen Ice Plates E', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 167),
('UW', 'Customer TCP 1', 'U', 'PAYMENT DEFERMENT', 'XCH', 'Extra Charges', 168),
('VA', 'Thermo Accessories', 'V', 'THERMO ACCESSORIES', 'FEE', 'Fees', 169),
('VB', 'Absorbent Sleeve', 'V', 'THERMO ACCESSORIES', 'XCH', 'Extra Charges', 170),
('VC', 'Cooland Wrap', 'V', 'THERMO ACCESSORIES', 'XCH', 'Extra Charges', 171),
('VD', 'Dry Ice Supplies', 'V', 'THERMO ACCESSORIES', 'XCH', 'Extra Charges', 172),
('VE', 'Pressure Bag S', 'V', 'THERMO ACCESSORIES', 'XCH', 'Extra Charges', 173),
('VF', 'Pressure Bag M', 'V', 'THERMO ACCESSORIES', 'XCH', 'Extra Charges', 174),
('VG', 'Pressure Bag L', 'V', 'THERMO ACCESSORIES', 'XCH', 'Extra Charges', 175),
('WA', 'Informal Clearance', 'W', 'CUSTOMS SERVICES', 'XCH', 'Extra Charges', 176),
('WB', 'Formal Clearance', 'W', 'CUSTOMS SERVICES', 'XCH', 'Extra Charges', 177),
('WC', 'Payment Deferment', 'W', 'CUSTOMS SERVICES', 'SCH', 'Surcharges', 178),
('WD', 'Clearance Authorization', 'W', 'CUSTOMS SERVICES', 'XCH', 'Extra Charges', 179),
('WE', 'Multiline Entry', 'W', 'CUSTOMS SERVICES', 'XCH', 'Extra Charges', 180),
('WF', 'Post Clearance Modification', 'W', 'CUSTOMS SERVICES', 'XCH', 'Extra Charges', 181),
('WG', 'Handover to Broker', 'W', 'CUSTOMS SERVICES', 'XCH', 'Extra Charges', 182),
('WH', 'Physical Intervention', 'W', 'CUSTOMS SERVICES', 'SCH', 'Surcharges', 183),
('WI', 'Bio/Phyto/Veterinary Controls', 'W', 'CUSTOMS SERVICES', 'SCH', 'Surcharges', 184),
('WJ', 'Obtaining Permits & Licences', 'W', 'CUSTOMS SERVICES', 'XCH', 'Extra Charges', 185),
('WK', 'Bonded Storage', 'W', 'CUSTOMS SERVICES', 'SCH', 'Surcharges', 186),
('WL', 'Bonded Transit Documents', 'W', 'CUSTOMS SERVICES', 'XCH', 'Extra Charges', 187),
('WM', 'Temporary Import/Export', 'W', 'CUSTOMS SERVICES', 'XCH', 'Extra Charges', 188),
('WN', 'Under Bond/Guarantee', 'W', 'CUSTOMS SERVICES', 'XCH', 'Extra Charges', 189),
('WO', 'Export Declaration', 'W', 'CUSTOMS SERVICES', 'XCH', 'Extra Charges', 190),
('WP', 'Exporter Validation', 'W', 'CUSTOMS SERVICES', 'XCH', 'Extra Charges', 191),
('WQ', 'Certificate of Origin', 'W', 'CUSTOMS SERVICES', 'XCH', 'Extra Charges', 192),
('WR', 'Document Translation', 'W', 'CUSTOMS SERVICES', 'XCH', 'Extra Charges', 193),
('WS', 'Personal Effects', 'W', 'CUSTOMS SERVICES', 'SCH', 'Surcharges', 194),
('WY', 'Paperless Trade', 'W', 'CUSTOMS SERVICES', 'INC', 'Included', 195),
('XB', 'Import Export Taxes', 'X', 'IMPORT/EXPORT DUTIES', 'FIS', 'Fiscal Features', 196),
('XC', 'Unrecoverable Origin Tax', 'X', 'IMPORT/EXPORT DUTIES', 'FIS', 'Fiscal Features', 197),
('XD', 'Quarantine Inspection', 'X', 'IMPORT/EXPORT DUTIES', 'FIS', 'Fiscal Features', 198),
('XE', 'Merchandise Process', 'X', 'IMPORT/EXPORT DUTIES', 'FIS', 'Fiscal Features', 199),
('XF', 'Domestic Postal Tax', 'X', 'IMPORT/EXPORT DUTIES', 'FIS', 'Fiscal Features', 200),
('XG', 'Tier Two Tax', 'X', 'IMPORT/EXPORT DUTIES', 'FIS', 'Fiscal Features', 201),
('XH', 'Tier Three Tax', 'X', 'IMPORT/EXPORT DUTIES', 'FIS', 'Fiscal Features', 202),
('XI', 'Import Penalty', 'X', 'IMPORT/EXPORT DUTIES', 'FIS', 'Fiscal Features', 203),
('XJ', 'Cargo Zone Process', 'X', 'IMPORT/EXPORT DUTIES', 'FIS', 'Fiscal Features', 204),
('XX', 'Import / Export Duties', 'X', 'IMPORT/EXPORT DUTIES', 'FIS', 'Fiscal Features', 205),
('Y1', '09:00 Premium', 'Y', 'NON STANDARD SHIPMENT', 'SCH', 'Surcharges', 206),
('Y2', '10:30 Premium', 'Y', 'NON STANDARD SHIPMENT', 'SCH', 'Surcharges', 207),
('Y3', '12:00 Premium', 'Y', 'NON STANDARD SHIPMENT', 'SCH', 'Surcharges', 208),
('YB', 'Over Sized Piece', 'Y', 'NON STANDARD SHIPMENT', 'SCH', 'Surcharges', 209),
('YC', 'Over Handled Piece', 'Y', 'NON STANDARD SHIPMENT', 'SCH', 'Surcharges', 210),
('YE', 'Multipiece Shipment', 'Y', 'NON STANDARD SHIPMENT', 'SCH', 'Surcharges', 211),
('YF', 'Over Weight Piece', 'Y', 'NON STANDARD SHIPMENT', 'SCH', 'Surcharges', 212),
('YG', 'Over Sized Piece', 'Y', 'NON STANDARD SHIPMENT', 'SCH', 'Surcharges', 213),
('YH', 'Over Handled Piece', 'Y', 'NON STANDARD SHIPMENT', 'SCH', 'Surcharges', 214),
('YI', '9:00 Premium', 'Y', 'NON STANDARD SHIPMENT', 'SCH', 'Surcharges', 215),
('YJ', '10:30 Premium', 'Y', 'NON STANDARD SHIPMENT', 'SCH', 'Surcharges', 216),
('YK', '12:00 Premium', 'Y', 'NON STANDARD SHIPMENT', 'SCH', 'Surcharges', 217),
('YV', 'Paket Shipment', 'Y', 'NON STANDARD SHIPMENT', 'INC', 'Included', 218),
('YW', 'Breakbulk Mother', 'Y', 'NON STANDARD SHIPMENT', 'INC', 'Included', 219),
('YX', 'Breakbulk Baby', 'Y', 'NON STANDARD SHIPMENT', 'INC', 'Included', 220),
('YY', 'Over Weight Piece', 'Y', 'NON STANDARD SHIPMENT', 'SCH', 'Surcharges', 221),
('ZA', 'Customer Claim', 'Z', 'UNRECOVERABLE ORIGIN TAX', 'CRE', 'Credit Items', 222),
('ZB', 'Damage Compensation', 'Z', 'UNRECOVERABLE ORIGIN TAX', 'CRE', 'Credit Items', 223),
('ZC', 'Loss Compensation', 'Z', 'UNRECOVERABLE ORIGIN TAX', 'CRE', 'Credit Items', 224),
('ZD', 'Customer Rebate', 'Z', 'UNRECOVERABLE ORIGIN TAX', 'CRE', 'Credit Items', 225),
('ZE', 'eCom Discount', 'Z', 'UNRECOVERABLE ORIGIN TAX', 'CRE', 'Credit Items', 226);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `dhl_special_services`
--
ALTER TABLE `dhl_special_services`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `dhl_special_services`
--
ALTER TABLE `dhl_special_services`
  MODIFY `id` int(11) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=227;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
