

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


-- --------------------------------------------------------

--
-- Table structure for table `dhl_country`
--

CREATE TABLE IF NOT EXISTS `dhl_country` (
  `ctry_cde` char(2) NOT NULL,
  `is_origin` char(1) NOT NULL,
  `region_cde` char(2) NOT NULL,
  `ctry_name` varchar(40) NOT NULL,
  `ctry_currency_cde` char(3) NOT NULL,
  `ctry_currency_name` varchar(30) NOT NULL,
  `uom_weight` char(2) NOT NULL,
  `uom_dim` char(2) NOT NULL,
  `loc_type_cde` char(2) NOT NULL,
  `loc_type_name` varchar(15) NOT NULL,
  `div_type_cde` char(2) NOT NULL,
  `div_type_name` varchar(15) NOT NULL,
  `id` int(11) unsigned NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=236 DEFAULT CHARSET=latin1 PACK_KEYS=1;

--
-- Dumping data for table `dhl_country`
--

INSERT INTO `dhl_country` (`ctry_cde`, `is_origin`, `region_cde`, `ctry_name`, `ctry_currency_cde`, `ctry_currency_name`, `uom_weight`, `uom_dim`, `loc_type_cde`, `loc_type_name`, `div_type_cde`, `div_type_name`, `id`) VALUES
('AD', 'P', 'EU', 'ANDORRA', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 2),
('AE', 'Y', 'AP', 'UNITED ARAB EMIRATES', 'AED', 'UAE Dirham', 'KG', 'CM', 'C', 'City', 'C', 'County', 3),
('AF', 'Y', 'AP', 'AFGHANISTAN', 'USD', 'US Dollar', 'KG', 'CM', 'C', 'City', '', '', 4),
('AG', 'Y', 'AM', 'ANTIGUA', 'XCD', 'East Caribbean Dollar', 'LB', 'IN', 'C', 'City', '', '', 5),
('AI', 'Y', 'AM', 'ANGUILLA', 'XCD', 'East Caribbean Dollar', 'LB', 'IN', 'S', 'Suburb', '', '', 6),
('AL', 'P', 'AP', 'ALBANIA', 'EUR', 'Euro', 'KG', 'CM', 'C', 'City', '', '', 7),
('AM', 'Y', 'AP', 'ARMENIA', 'AMD', 'Dran', 'KG', 'CM', 'CP', 'City Postcode', 'C', 'County', 8),
('AN', 'Y', 'AM', 'NETHERLANDS ANTILLES', 'ANG', 'Netherlands Antilles Guilder', 'KG', 'CM', 'C', 'City', 'C', 'County', 9),
('AO', 'Y', 'AP', 'ANGOLA', 'AOA', 'Kwanza', 'KG', 'CM', 'C', 'City', '', '', 10),
('AR', 'Y', 'AM', 'ARGENTINA', 'ARS', 'Argentine Peso', 'KG', 'CM', 'CP', 'City Postcode', '', '', 11),
('AS', 'Y', 'AM', 'AMERICAN SAMOA', 'USD', 'US Dollar', 'LB', 'IN', 'CP', 'City Postcode', '', '', 12),
('AT', 'Y', 'EU', 'AUSTRIA', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 13),
('AU', 'Y', 'AP', 'AUSTRALIA', 'AUD', 'Australian Dollar', 'KG', 'CM', 'CP', 'City Postcode', 'S', 'STATE', 14),
('AW', 'Y', 'AM', 'ARUBA', 'AWG', 'Aruba Guilder', 'LB', 'IN', 'C', 'City', '', '', 15),
('AZ', 'Y', 'AM', 'AZERBAIJAN', 'AZN', 'Manat', 'KG', 'CM', 'CP', 'City Postcode', 'C', 'County', 16),
('BA', 'Y', 'AP', 'BOSNIA AND HERZEGOVINA', 'BAM', 'Convertible Marks', 'KG', 'CM', 'CP', 'City Postcode', 'C', 'County', 17),
('BB', 'Y', 'AM', 'BARBADOS', 'BBD', 'Barbadian Dollar', 'LB', 'IN', 'C', 'City', '', '', 18),
('BD', 'Y', 'AP', 'BANGLADESH', 'BDT', 'Taka', 'KG', 'CM', 'CP', 'City Postcode', 'C', 'County', 19),
('BE', 'Y', 'EU', 'BELGIUM', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 20),
('BF', 'Y', 'AP', 'BURKINA FASO', 'XOF', 'CFA Franc - West Africa', 'KG', 'CM', 'C', 'City', '', '', 21),
('BG', 'Y', 'EU', 'BULGARIA', 'BGN', 'Bulgarian Lev', 'KG', 'CM', 'CP', 'City Postcode', '', '', 22),
('BH', 'Y', 'AP', 'BAHRAIN', 'BHD', 'Bahraini Dinar', 'KG', 'CM', 'C', 'City', '', '', 23),
('BI', 'Y', 'AP', 'BURUNDI', 'BIF', 'Burundese Franc', 'KG', 'CM', 'C', 'City', '', '', 24),
('BJ', 'Y', 'AP', 'BENIN', 'XOF', 'CFA Franc - West Africa', 'KG', 'CM', 'C', 'City', '', '', 25),
('BM', 'Y', 'AM', 'BERMUDA', 'BMD', 'Bermudian Dollar', 'LB', 'IN', 'C', 'City', '', '', 26),
('BN', 'Y', 'AP', 'BRUNEI', 'BND', 'Brunei Dollar', 'KG', 'CM', 'CP', 'City Postcode', 'C', 'County', 27),
('BO', 'Y', 'AM', 'BOLIVIA', 'BOB', 'Boliviano', 'KG', 'CM', 'C', 'City', '', '', 28),
('BR', 'Y', 'AM', 'BRAZIL', 'BRL', 'Real', 'KG', 'CM', 'CP', 'City Postcode', '', '', 29),
('BS', 'Y', 'AM', 'BAHAMAS', 'BSD', 'Bahamian Dollar', 'LB', 'IN', 'C', 'City', '', '', 30),
('BT', 'Y', 'AP', 'BHUTAN', 'BTN', 'Ngultrum', 'KG', 'CM', 'C', 'City', '', '', 31),
('BW', 'Y', 'AP', 'BOTSWANA', 'BWP', 'Pula', 'KG', 'CM', 'C', 'City', '', '', 32),
('BY', 'Y', 'AP', 'BELARUS', 'BYN', 'Belarussian Ruble', 'KG', 'CM', 'CP', 'City Postcode', 'C', 'County', 33),
('BZ', 'P', 'AM', 'BELIZE', 'BZD', 'Belize Dollar', 'KG', 'CM', 'C', 'City', 'N/', '', 34),
('CA', 'Y', 'AM', 'CANADA', 'CAD', 'Canadian Dollar', 'LB', 'IN', 'CP', 'City Postcode', 'P', 'PROVINCE', 35),
('CD', 'Y', 'AP', 'CONGO, THE DEMOCRATIC REPUBLIC OF', 'CDF', 'Franc Congolais', 'KG', 'CM', 'C', 'City', '', '', 36),
('CF', 'Y', 'AP', 'CENTRAL AFRICAN REPUBLIC', 'XAF', 'CFA Franc - Central Africa', 'KG', 'CM', 'C', 'City', '', '', 37),
('CG', 'Y', 'AP', 'CONGO', 'XAF', 'CFA Franc - Central Africa', 'KG', 'CM', 'C', 'City', '', '', 38),
('CH', 'Y', 'EU', 'SWITZERLAND', 'CHF', 'Swiss Franc', 'KG', 'CM', 'CP', 'City Postcode', '', '', 39),
('CI', 'Y', 'AP', 'COTE D IVOIRE', 'XOF', 'CFA Franc - West Africa', 'KG', 'CM', 'C', 'City', '', '', 40),
('CK', 'P', 'AP', 'COOK ISLANDS', 'NZD', 'New Zealand Dollar', 'KG', 'CM', 'C', 'City', '', '', 41),
('CL', 'Y', 'AM', 'CHILE', 'CLP', 'New Chile Peso', 'KG', 'CM', 'C', 'City', '', '', 42),
('CM', 'Y', 'AP', 'CAMEROON', 'XAF', 'CFA Franc - Central Africa', 'KG', 'CM', 'C', 'City', '', '', 43),
('CN', 'Y', 'AP', 'CHINA, PEOPLES REPUBLIC', 'CNY', 'Yuan (Ren Min Bi)', 'KG', 'CM', 'CP', 'City Postcode', '', '', 44),
('CO', 'Y', 'AM', 'COLOMBIA', 'COP', 'Colombian Peso', 'KG', 'CM', 'CP', 'City Postcode', '', '', 45),
('CR', 'Y', 'AM', 'COSTA RICA', 'CRC', 'Costa Rican Colon', 'KG', 'CM', 'C', 'City', '', '', 46),
('CU', 'P', 'AM', 'CUBA', 'CUC', 'Peso Convertible', 'KG', 'CM', 'CP', 'City Postcode', '', '', 47),
('CV', 'P', 'AP', 'CAPE VERDE', 'CVE', 'Cape Verde Escudo', 'KG', 'CM', 'C', 'City', '', '', 48),
('CY', 'Y', 'AP', 'CYPRUS', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 49),
('CZ', 'Y', 'EU', 'CZECH REPUBLIC, THE', 'CZK', 'Czech Koruna', 'KG', 'CM', 'CP', 'City Postcode', '', '', 50),
('DE', 'Y', 'EU', 'GERMANY', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 51),
('DJ', 'P', 'AP', 'DJIBOUTI', 'DJF', 'Djibouti Franc', 'KG', 'CM', 'C', 'City', '', '', 52),
('DK', 'Y', 'EU', 'DENMARK', 'DKK', 'Danish Krone', 'KG', 'CM', 'CP', 'City Postcode', '', '', 53),
('DM', 'Y', 'AM', 'DOMINICA', 'XCD', 'East Caribbean Dollar', 'LB', 'IN', 'C', 'City', '', '', 54),
('DO', 'Y', 'AM', 'DOMINICAN REPUBLIC', 'DOP', 'Dominican Republic Peso', 'LB', 'IN', 'C', 'City', '', '', 55),
('DZ', 'Y', 'AP', 'ALGERIA', 'DZD', 'Algerian Dinar', 'KG', 'CM', 'CP', 'City Postcode', '', '', 56),
('EC', 'Y', 'AM', 'ECUADOR', 'USD', 'US Dollar', 'KG', 'CM', 'CP', 'City Postcode', '', '', 57),
('EE', 'Y', 'EU', 'ESTONIA', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 58),
('EG', 'Y', 'AP', 'EGYPT', 'EGP', 'Egyptian Pound', 'KG', 'CM', 'C', 'City', '', '', 59),
('ER', 'P', 'AP', 'ERITREA', 'ERN', 'Nakfa', 'KG', 'CM', 'C', 'City', '', '', 60),
('ES', 'Y', 'EU', 'SPAIN', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 61),
('ET', 'Y', 'AP', 'ETHIOPIA', 'ETB', 'Birr', 'KG', 'CM', 'C', 'City', '', '', 62),
('FI', 'Y', 'EU', 'FINLAND', 'EUR', 'Euro', 'KG', 'CM', 'P', 'Postcode', '', '', 63),
('FJ', 'Y', 'AP', 'FIJI', 'FJD', 'Fijian Dollar', 'KG', 'CM', 'C', 'City', '', '', 64),
('FK', 'P', 'EU', 'FALKLAND ISLANDS', 'GBP', 'Pound Sterling', 'KG', 'CM', 'C', 'City', '', '', 65),
('FM', 'P', 'AM', 'MICRONESIA, FEDERATED STATES OF', 'USD', 'US Dollar', 'LB', 'IN', 'CP', 'City Postcode', '', '', 66),
('FO', 'P', 'AM', 'FAROE ISLANDS', 'DKK', 'Danish Krone', 'KG', 'CM', 'CP', 'City Postcode', '', '', 67),
('FR', 'Y', 'EU', 'FRANCE', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 68),
('GA', 'Y', 'AP', 'GABON', 'XAF', 'CFA Franc - Central Africa', 'KG', 'CM', 'C', 'City', '', '', 69),
('GB', 'Y', 'EU', 'UNITED KINGDOM', 'GBP', 'Pound Sterling', 'KG', 'CM', 'CP', 'City Postcode', 'C', 'County', 70),
('GD', 'Y', 'AM', 'GRENADA', 'XCD', 'East Caribbean Dollar', 'LB', 'IN', 'C', 'City', '', '', 71),
('GE', 'Y', 'AM', 'GEORGIA', 'GEL', 'Georgian Lari', 'KG', 'CM', 'CP', 'City Postcode', 'C', 'County', 72),
('GF', 'Y', 'AM', 'FRENCH GUYANA', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 73),
('GG', 'P', 'EU', 'GUERNSEY', 'GBP', 'Pound Sterling', 'KG', 'CM', 'CP', 'City Postcode', '', '', 74),
('GH', 'Y', 'AP', 'GHANA', 'GHS', 'Cedi', 'KG', 'CM', 'C', 'City', '', '', 75),
('GI', 'P', 'EU', 'GIBRALTAR', 'GBP', 'Pound Sterling', 'KG', 'CM', 'C', 'City', '', '', 76),
('GL', 'P', 'AM', 'GREENLAND', 'DKK', 'Danish Krone', 'KG', 'CM', 'CP', 'City Postcode', '', '', 77),
('GM', 'Y', 'AP', 'GAMBIA', 'GMD', 'Dalasi', 'KG', 'CM', 'C', 'City', '', '', 78),
('GN', 'Y', 'AP', 'GUINEA REPUBLIC', 'GNF', 'Guinea Franc', 'KG', 'CM', 'C', 'City', '', '', 79),
('GP', 'Y', 'AM', 'GUADELOUPE', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 80),
('GQ', 'Y', 'AP', 'GUINEA-EQUATORIAL', 'XAF', 'CFA Franc - Central Africa', 'KG', 'CM', 'C', 'City', '', '', 81),
('GR', 'Y', 'EU', 'GREECE', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 82),
('GT', 'Y', 'AM', 'GUATEMALA', 'GTQ', 'Quetzal', 'KG', 'CM', 'C', 'City', '', '', 83),
('GU', 'Y', 'AM', 'GUAM', 'USD', 'US Dollar', 'LB', 'IN', 'CP', 'City Postcode', '', '', 84),
('GW', 'Y', 'AP', 'GUINEA-BISSAU', 'XOF', 'CFA Franc - West Africa', 'KG', 'CM', 'C', 'City', '', '', 85),
('GY', 'Y', 'AP', 'GUYANA (BRITISH)', 'GYD', 'Guyanan Dollar', 'LB', 'IN', 'C', 'City', '', '', 86),
('HK', 'Y', 'AP', 'HONG KONG', 'HKD', 'Hong Kong Dollar', 'KG', 'CM', 'C', 'City', '', '', 87),
('HN', 'Y', 'AM', 'HONDURAS', 'HNL', 'Lempira', 'KG', 'CM', 'C', 'City', '', '', 88),
('HR', 'Y', 'AP', 'CROATIA', 'HRK', 'Croatian Kuna', 'KG', 'CM', 'CP', 'City Postcode', '', '', 89),
('HT', 'Y', 'AM', 'HAITI', 'HTG', 'Gourde', 'LB', 'IN', 'C', 'City', '', '', 90),
('HU', 'Y', 'EU', 'HUNGARY', 'HUF', 'Forint', 'KG', 'CM', 'CP', 'City Postcode', '', '', 91),
('IC', 'P', 'EU', 'CANARY ISLANDS, THE', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 92),
('ID', 'Y', 'AP', 'INDONESIA', 'IDR', 'Rupiah', 'KG', 'CM', 'CP', 'City Postcode', '', '', 93),
('IE', 'Y', 'EU', 'IRELAND, REPUBLIC OF', 'EUR', 'Euro', 'KG', 'CM', 'S', 'Suburb', 'C', 'County', 94),
('IL', 'Y', 'AP', 'ISRAEL', 'ILS', 'New Israeli Shekel', 'KG', 'CM', 'CP', 'City Postcode', '', '', 95),
('IN', 'Y', 'AP', 'INDIA', 'INR', 'Indian Rupee', 'KG', 'CM', 'CP', 'City Postcode', 'C', 'County', 96),
('IQ', 'Y', 'AP', 'IRAQ', 'USD', 'US Dollar', 'KG', 'CM', 'C', 'City', '', '', 97),
('IR', 'Y', 'AP', 'IRAN (ISLAMIC REPUBLIC OF)', 'IRR', 'Iranian Rial', 'KG', 'CM', 'C', 'City', '', '', 98),
('IS', 'Y', 'EU', 'ICELAND', 'ISK', 'Icelandic Krona', 'KG', 'CM', 'CP', 'City Postcode', '', '', 99),
('IT', 'Y', 'EU', 'ITALY', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', 'C', 'County', 100),
('JE', 'P', 'EU', 'JERSEY', 'GBP', 'Pound Sterling', 'KG', 'CM', 'CP', 'City Postcode', '', '', 101),
('JM', 'Y', 'AM', 'JAMAICA', 'JMD', 'Jamaican Dollar', 'KG', 'CM', 'C', 'City', '', '', 102),
('JO', 'Y', 'AP', 'JORDAN', 'JOD', 'Jordanian Dinar', 'KG', 'CM', 'S', 'Suburb', '', '', 103),
('JP', 'Y', 'AP', 'JAPAN', 'JPY', 'Yen', 'KG', 'CM', 'CP', 'City Postcode', 'S', 'STATE', 104),
('KE', 'Y', 'AP', 'KENYA', 'KES', 'Kenyan Shilling', 'KG', 'CM', 'C', 'City', '', '', 105),
('KG', 'Y', 'AP', 'KYRGYZSTAN', 'KGS', 'Som', 'KG', 'CM', 'CP', 'City Postcode', 'C', 'County', 106),
('KH', 'Y', 'AP', 'CAMBODIA', 'KHR', 'Khmer Rial', 'KG', 'CM', 'CP', 'City Postcode', '', '', 107),
('KI', 'P', 'AP', 'KIRIBATI', 'AUD', 'Australian Dollar', 'KG', 'CM', 'C', 'City', '', '', 108),
('KM', 'Y', 'AP', 'COMOROS', 'KMF', 'Comoros Franc', 'KG', 'CM', 'C', 'City', '', '', 109),
('KN', 'Y', 'AM', 'ST. KITTS', 'XCD', 'East Caribbean Dollar', 'LB', 'IN', 'C', 'City', '', '', 110),
('KP', 'Y', 'AP', 'KOREA, THE D.P.R OF (NORTH K.)', 'KPW', 'North Korean Won', 'KG', 'CM', 'C', 'City', '', '', 111),
('KR', 'Y', 'AP', 'KOREA, REPUBLIC OF (SOUTH K.)', 'KRW', 'Won', 'KG', 'CM', 'CP', 'City Postcode', '', '', 112),
('KV', 'P', 'AM', 'KOSOVO', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 113),
('KW', 'Y', 'AP', 'KUWAIT', 'KWD', 'Kuwaiti Dinar', 'KG', 'CM', 'C', 'City', '', '', 114),
('KY', 'Y', 'AM', 'CAYMAN ISLANDS', 'KYD', 'Cayman Islands Dollar', 'LB', 'IN', 'C', 'City', '', '', 115),
('KZ', 'Y', 'AP', 'KAZAKHSTAN', 'KZT', 'Tenge', 'KG', 'CM', 'CP', 'City Postcode', 'C', 'County', 116),
('LA', 'Y', 'AP', 'LAO PEOPLES DEMOCRATIC REPUBLIC', 'LAK', 'Kip', 'KG', 'CM', 'C', 'City', '', '', 117),
('LB', 'Y', 'AP', 'LEBANON', 'USD', 'US Dollar', 'KG', 'CM', 'C', 'City', '', '', 118),
('LC', 'Y', 'AM', 'ST. LUCIA', 'XCD', 'East Caribbean Dollar', 'LB', 'IN', 'C', 'City', '', '', 119),
('LI', 'P', 'AM', 'LIECHTENSTEIN', 'CHF', 'Swiss Franc', 'KG', 'CM', 'CP', 'City Postcode', '', '', 120),
('LK', 'Y', 'AP', 'SRI LANKA', 'LKR', 'Sri Lankan Rupee', 'KG', 'CM', 'C', 'City', '', '', 121),
('LR', 'Y', 'AP', 'LIBERIA', 'LRD', 'Liberian Dollar', 'KG', 'CM', 'C', 'City', '', '', 122),
('LS', 'Y', 'AP', 'LESOTHO', 'LSL', 'Loti', 'KG', 'CM', 'C', 'City', '', '', 123),
('LT', 'Y', 'EU', 'LITHUANIA', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 124),
('LU', 'Y', 'EU', 'LUXEMBOURG', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 125),
('LV', 'Y', 'EU', 'LATVIA', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 126),
('LY', 'Y', 'AP', 'LIBYA', 'LYD', 'Libyan Dinar', 'KG', 'CM', 'C', 'City', '', '', 127),
('MA', 'Y', 'AP', 'MOROCCO', 'MAD', 'Moroccan Dirham', 'KG', 'CM', 'CP', 'City Postcode', '', '', 128),
('MC', 'P', 'AM', 'MONACO', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 129),
('MD', 'Y', 'AP', 'MOLDOVA, REPUBLIC OF', 'MDL', 'Leu', 'KG', 'CM', 'CP', 'City Postcode', 'C', 'County', 130),
('ME', 'P', 'AM', 'MONTENEGRO, REPUBLIC OF', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 131),
('MG', 'Y', 'AP', 'MADAGASCAR', 'MGA', 'Ariary', 'KG', 'CM', 'CP', 'City Postcode', '', '', 132),
('MH', 'P', 'AM', 'MARSHALL ISLANDS', 'USD', 'US Dollar', 'LB', 'IN', 'CP', 'City Postcode', '', '', 133),
('MK', 'Y', 'AP', 'MACEDONIA, REPUBLIC OF', 'MKD', 'Denar', 'KG', 'CM', 'CP', 'City Postcode', '', '', 134),
('ML', 'Y', 'AP', 'MALI', 'XOF', 'CFA Franc - West Africa', 'KG', 'CM', 'C', 'City', '', '', 135),
('MM', 'Y', 'AP', 'MYANMAR', 'MMK', 'Kyat', 'KG', 'CM', 'C', 'City', '', '', 136),
('MN', 'Y', 'AP', 'MONGOLIA', 'MNT', 'Tugrik', 'KG', 'CM', 'CP', 'City Postcode', '', '', 137),
('MO', 'P', 'AP', 'MACAU', 'MOP', 'Pataca', 'KG', 'CM', 'C', 'City', '', '', 138),
('MP', 'Y', 'AM', 'COMMONWEALTH NO. MARIANA ISLANDS', 'USD', 'US Dollar', 'LB', 'IN', 'CP', 'City Postcode', '', '', 139),
('MQ', 'Y', 'AM', 'MARTINIQUE', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 140),
('MR', 'Y', 'AP', 'MAURITANIA', 'MRO', 'Ouguiya', 'KG', 'CM', 'C', 'City', '', '', 141),
('MS', 'P', 'AM', 'MONTSERRAT', 'XCD', 'East Caribbean Dollar', 'LB', 'IN', 'C', 'City', '', '', 142),
('MT', 'Y', 'AP', 'MALTA', 'EUR', 'Euro', 'KG', 'CM', 'C', 'City', '', '', 143),
('MU', 'Y', 'AP', 'MAURITIUS', 'MUR', 'Mauritius Rupee', 'KG', 'CM', 'C', 'City', '', '', 144),
('MV', 'Y', 'AP', 'MALDIVES', 'MVR', 'Rufiyaa', 'KG', 'CM', 'CP', 'City Postcode', '', '', 145),
('MW', 'Y', 'AP', 'MALAWI', 'MWK', 'Kwacha', 'KG', 'CM', 'C', 'City', '', '', 146),
('MX', 'Y', 'AM', 'MEXICO', 'MXN', 'Mexican Nuevo Peso', 'KG', 'CM', 'CP', 'City Postcode', '', '', 147),
('MY', 'Y', 'AP', 'MALAYSIA', 'MYR', 'Ringgit', 'KG', 'CM', 'CP', 'City Postcode', '', '', 148),
('MZ', 'Y', 'AP', 'MOZAMBIQUE', 'MZN', 'Mozambique Metical', 'KG', 'CM', 'C', 'City', '', '', 149),
('NA', 'Y', 'AP', 'NAMIBIA', 'NAD', 'Namibian Dollar', 'KG', 'CM', 'C', 'City', '', '', 150),
('NC', 'P', 'AP', 'NEW CALEDONIA', 'XPF', 'CFP Franc', 'KG', 'CM', 'CP', 'City Postcode', '', '', 151),
('NE', 'Y', 'AP', 'NIGER', 'XOF', 'CFA Franc - West Africa', 'KG', 'CM', 'C', 'City', '', '', 152),
('NG', 'Y', 'AP', 'NIGERIA', 'NGN', 'Naira', 'KG', 'CM', 'C', 'City', '', '', 153),
('NI', 'Y', 'AM', 'NICARAGUA', 'NIO', 'Cordoba Oro', 'KG', 'CM', 'C', 'City', '', '', 154),
('NL', 'Y', 'EU', 'NETHERLANDS, THE', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 155),
('NO', 'Y', 'EU', 'NORWAY', 'NOK', 'Norwegian Krone', 'KG', 'CM', 'CP', 'City Postcode', '', '', 156),
('NP', 'Y', 'AP', 'NEPAL', 'NPR', 'Nepalese Rupee', 'KG', 'CM', 'C', 'City', '', '', 157),
('NR', 'P', 'AP', 'NAURU, REPUBLIC OF', 'AUD', 'Australian Dollar', 'KG', 'CM', 'C', 'City', '', '', 158),
('NU', 'P', 'AP', 'NIUE', 'NZD', 'New Zealand Dollar', 'KG', 'CM', 'C', 'City', '', '', 159),
('NZ', 'Y', 'AP', 'NEW ZEALAND', 'NZD', 'New Zealand Dollar', 'KG', 'CM', 'CP', 'City Postcode', '', '', 160),
('OM', 'Y', 'AP', 'OMAN', 'OMR', 'Omani Rial', 'KG', 'CM', 'C', 'City', '', '', 161),
('PA', 'Y', 'AM', 'PANAMA', 'USD', 'US Dollar', 'KG', 'CM', 'C', 'City', '', '', 162),
('PE', 'Y', 'AM', 'PERU', 'PEN', 'Nuevo Sol', 'KG', 'CM', 'C', 'City', '', '', 163),
('PF', 'P', 'AP', 'TAHITI', 'XPF', 'CFP Franc', 'KG', 'CM', 'C', 'City', '', '', 164),
('PG', 'Y', 'AP', 'PAPUA NEW GUINEA', 'PGK', 'Kina', 'KG', 'CM', 'CP', 'City Postcode', 'P', 'PROVINCE', 165),
('PH', 'Y', 'AP', 'PHILIPPINES, THE', 'PHP', 'Phillipines Peso', 'KG', 'CM', 'CP', 'City Postcode', 'C', 'County', 166),
('PK', 'Y', 'AP', 'PAKISTAN', 'PKR', 'Pakistani Rupee', 'KG', 'CM', 'P', 'Postcode', '', '', 167),
('PL', 'Y', 'EU', 'POLAND', 'PLN', 'Zloty', 'KG', 'CM', 'CP', 'City Postcode', '', '', 168),
('PR', 'Y', 'AM', 'PUERTO RICO', 'USD', 'US Dollar', 'LB', 'IN', 'CP', 'City Postcode', '', '', 169),
('PT', 'Y', 'EU', 'PORTUGAL', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 170),
('PW', 'P', 'AM', 'PALAU', 'USD', 'US Dollar', 'KG', 'CM', 'CP', 'City Postcode', '', '', 171),
('PY', 'Y', 'AM', 'PARAGUAY', 'PYG', 'Guarani', 'KG', 'CM', 'C', 'City', '', '', 172),
('QA', 'Y', 'AP', 'QATAR', 'QAR', 'Qatar Rial', 'KG', 'CM', 'C', 'City', '', '', 173),
('RE', 'Y', 'AP', 'REUNION, ISLAND OF', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 174),
('RO', 'Y', 'EU', 'ROMANIA', 'RON', 'Leu', 'KG', 'CM', 'CP', 'City Postcode', '', '', 175),
('RS', 'Y', 'AP', 'SERBIA, REPUBLIC OF', 'RSD', 'Serbia, Dinars', 'KG', 'CM', 'CP', 'City Postcode', '', '', 176),
('RU', 'Y', 'AP', 'RUSSIAN FEDERATION, THE', 'RUB', 'Russian Ruble', 'KG', 'CM', 'CP', 'City Postcode', '', '', 177),
('RW', 'Y', 'AP', 'RWANDA', 'RWF', 'Rwanda Franc', 'KG', 'CM', 'C', 'City', '', '', 178),
('SA', 'Y', 'AP', 'SAUDI ARABIA', 'SAR', 'Saudi Riyal', 'KG', 'CM', 'C', 'City', '', '', 179),
('SB', 'P', 'AP', 'SOLOMON ISLANDS', 'SBD', 'Solomon Islands Dollar', 'KG', 'CM', 'C', 'City', '', '', 180),
('SC', 'Y', 'AP', 'SEYCHELLES', 'SCR', 'Seychelles Rupee', 'KG', 'CM', 'C', 'City', '', '', 181),
('SD', 'Y', 'AP', 'SUDAN', 'SDG', 'Sudanese Pound', 'KG', 'CM', 'C', 'City', '', '', 182),
('SE', 'Y', 'EU', 'SWEDEN', 'SEK', 'Swedish Krona', 'KG', 'CM', 'CP', 'City Postcode', 'C', 'County', 183),
('SG', 'Y', 'AP', 'SINGAPORE', 'SGD', 'Singapore Dollar', 'KG', 'CM', 'CP', 'City Postcode', 'S', 'STATE', 184),
('SH', 'P', 'AP', 'SAINT HELENA', 'SHP', 'St. Helena Pound', 'KG', 'CM', 'S', 'Suburb', 'D', 'District', 185),
('SI', 'Y', 'EU', 'SLOVENIA', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 186),
('SK', 'Y', 'EU', 'SLOVAKIA', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 187),
('SL', 'Y', 'AP', 'SIERRA LEONE', 'SLL', 'Leone', 'KG', 'CM', 'C', 'City', '', '', 188),
('SM', 'P', 'EU', 'SAN MARINO', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 189),
('SN', 'Y', 'AP', 'SENEGAL', 'XOF', 'CFA Franc - West Africa', 'KG', 'CM', 'C', 'City', '', '', 190),
('SO', 'P', 'AM', 'SOMALIA', 'SOS', 'Somali Shilling', 'KG', 'CM', 'C', 'City', '', '', 191),
('SR', 'Y', 'AM', 'SURINAME', 'SRD', 'Suriname Dollar', 'KG', 'CM', 'C', 'City', '', '', 192),
('SS', 'Y', 'AP', 'SOUTH SUDAN', 'SSP', 'South Sudanese pound', 'KG', 'CM', 'C', 'City', '', '', 193),
('ST', 'P', 'AP', 'SAO TOME AND PRINCIPE', 'STD', 'Dobra', 'KG', 'CM', 'C', 'City', '', '', 194),
('SV', 'Y', 'AM', 'EL SALVADOR', 'USD', 'US Dollar', 'KG', 'CM', 'C', 'City', '', '', 195),
('SY', 'Y', 'AP', 'SYRIA', 'SYP', 'Syrian Pound', 'KG', 'CM', 'C', 'City', 'P', 'PROVINCE', 196),
('SZ', 'Y', 'AP', 'SWAZILAND', 'SZL', 'Lilangeni', 'KG', 'CM', 'CP', 'City Postcode', '', '', 197),
('TC', 'Y', 'AM', 'TURKS AND CAICOS ISLANDS', 'USD', 'US Dollar', 'LB', 'IN', 'C', 'City', '', '', 198),
('TD', 'Y', 'AP', 'CHAD', 'XAF', 'CFA Franc - Central Africa', 'KG', 'CM', 'C', 'City', '', '', 199),
('TG', 'Y', 'AP', 'TOGO', 'XOF', 'CFA Franc - West Africa', 'KG', 'CM', 'C', 'City', '', '', 200),
('TH', 'Y', 'AP', 'THAILAND', 'THB', 'Baht', 'KG', 'CM', 'CP', 'City Postcode', '', '', 201),
('TJ', 'Y', 'AP', 'TAJIKISTAN', 'TJS', 'Somoni', 'KG', 'CM', 'CP', 'City Postcode', 'C', 'County', 202),
('TL', 'Y', 'AP', 'TIMOR LESTE', 'USD', 'US Dollar', 'KG', 'CM', 'C', 'City', '', '', 203),
('TN', 'Y', 'AP', 'TUNISIA', 'TND', 'Tunisian Dinar', 'KG', 'CM', 'CP', 'City Postcode', '', '', 204),
('TO', 'P', 'AP', 'TONGA', 'TOP', 'Pa''anga', 'KG', 'CM', 'C', 'City', '', '', 205),
('TR', 'Y', 'AP', 'TURKEY', 'TRY', 'New Turkish Lira', 'KG', 'CM', 'CP', 'City Postcode', '', '', 206),
('TT', 'Y', 'AM', 'TRINIDAD AND TOBAGO', 'TTD', 'Trinidad and Tobago Dollar', 'LB', 'IN', 'C', 'City', '', '', 207),
('TV', 'P', 'AP', 'TUVALU', 'AUD', 'Australian Dollar', 'KG', 'CM', 'C', 'City', '', '', 208),
('TW', 'Y', 'AP', 'TAIWAN', 'TWD', 'New Taiwan Dollar', 'KG', 'CM', 'CP', 'City Postcode', '', '', 209),
('TZ', 'Y', 'AP', 'TANZANIA', 'TZS', 'Tanzanian Shilling', 'KG', 'CM', 'C', 'City', '', '', 210),
('UA', 'Y', 'AP', 'UKRAINE', 'UAH', 'Hryvna', 'KG', 'CM', 'CP', 'City Postcode', 'S', 'STATE', 211),
('UG', 'Y', 'AP', 'UGANDA', 'USD', 'US Dollar', 'KG', 'CM', 'C', 'City', '', '', 212),
('US', 'Y', 'AM', 'UNITED STATES OF AMERICA', 'USD', 'US Dollar', 'LB', 'IN', 'CP', 'City Postcode', 'S', 'STATE', 213),
('UY', 'Y', 'AM', 'URUGUAY', 'UYU', 'Peso Uruguayo', 'KG', 'CM', 'C', 'City', '', '', 214),
('UZ', 'Y', 'AP', 'UZBEKISTAN', 'UZS', 'Sum', 'KG', 'CM', 'CP', 'City Postcode', 'C', 'County', 215),
('VA', 'Y', 'No', 'VATICAN CITY STATE', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 216),
('VC', 'Y', 'AM', 'ST. VINCENT', 'XCD', 'East Caribbean Dollar', 'LB', 'IN', 'C', 'City', '', '', 217),
('VE', 'Y', 'AM', 'VENEZUELA', 'VEF', 'Bolivar Fuerte', 'KG', 'CM', 'C', 'City', '', '', 218),
('VG', 'Y', 'AM', 'VIRGIN ISLANDS (BRITISH)', 'USD', 'US Dollar', 'LB', 'IN', 'C', 'City', '', '', 219),
('VI', 'Y', 'AM', 'VIRGIN ISLANDS (US)', 'USD', 'US Dollar', 'LB', 'IN', 'CP', 'City Postcode', '', '', 220),
('VN', 'Y', 'AP', 'VIETNAM', 'VND', 'Dong', 'KG', 'CM', 'C', 'City', '', '', 221),
('VU', 'P', 'AP', 'VANUATU', 'VUV', 'Vanuatu Vatu', 'KG', 'CM', 'C', 'City', '', '', 222),
('WS', 'P', 'AP', 'SAMOA', 'WST', 'Tala', 'KG', 'CM', 'C', 'City', '', '', 223),
('XB', 'P', 'AM', 'BONAIRE', 'EUR', 'Euro', 'LB', 'IN', 'C', 'City', '', '', 224),
('XC', 'Y', 'AM', 'CURACAO', 'EUR', 'Euro', 'LB', 'IN', 'C', 'City', '', '', 225),
('XE', 'P', 'AM', 'ST. EUSTATIUS', 'ANG', 'Netherlands Antilles Guilder', 'LB', 'IN', 'C', 'City', '', '', 226),
('XM', 'Y', 'AM', 'ST. MAARTEN', 'EUR', 'Euro', 'LB', 'IN', 'C', 'City', '', '', 227),
('XN', 'Y', 'AM', 'NEVIS', 'XCD', 'East Caribbean Dollar', 'LB', 'IN', 'C', 'City', '', '', 228),
('XS', 'P', 'AP', 'SOMALILAND, REP OF (NORTH SOMALIA)', 'USD', 'US Dollar', 'KG', 'CM', 'C', 'City', '', '', 229),
('XY', 'Y', 'AM', 'ST. BARTHELEMY', 'ANG', 'Netherlands Antilles Guilder', 'LB', 'IN', 'CP', 'City Postcode', '', '', 230),
('YE', 'Y', 'AP', 'YEMEN, REPUBLIC OF', 'YER', 'Yemeni Riyal', 'KG', 'CM', 'C', 'City', '', '', 231),
('YT', 'Y', 'AP', 'MAYOTTE', 'EUR', 'Euro', 'KG', 'CM', 'CP', 'City Postcode', '', '', 232),
('ZA', 'Y', 'AP', 'SOUTH AFRICA', 'ZAR', 'South African Rand', 'KG', 'CM', 'CP', 'City Postcode', '', '', 233),
('ZM', 'Y', 'AP', 'ZAMBIA', 'ZMW', 'Kwacha', 'KG', 'CM', 'C', 'City', '', '', 234),
('ZW', 'Y', 'AP', 'ZIMBABWE', 'USD', 'US Dollar', 'KG', 'CM', 'C', 'City', '', '', 235);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `dhl_country`
--
ALTER TABLE `dhl_country`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `dhl_country`
--
ALTER TABLE `dhl_country`
  MODIFY `id` int(11) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=236;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
