
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


-- --------------------------------------------------------

--
-- Table structure for table `dhl_language`
--

CREATE TABLE IF NOT EXISTS `dhl_language` (
  `ctry_cde` char(2) NOT NULL,
  `lang_cde` char(2) NOT NULL,
  `lang_name` varchar(20) NOT NULL,
  `id` int(11) unsigned NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=319 DEFAULT CHARSET=latin1 PACK_KEYS=1;

--
-- Dumping data for table `dhl_language`
--

INSERT INTO `dhl_language` (`ctry_cde`, `lang_cde`, `lang_name`, `id`) VALUES
('AD', 'en', 'English', 2),
('AF', 'en', 'English', 3),
('AG', 'en', 'English', 4),
('AI', 'en', 'English', 5),
('AL', 'en', 'English', 6),
('AM', 'en', 'English', 7),
('AN', 'en', 'English', 8),
('AS', 'en', 'English', 9),
('AW', 'en', 'English', 10),
('AZ', 'en', 'English', 11),
('BA', 'en', 'English', 12),
('BF', 'en', 'English', 13),
('BI', 'en', 'English', 14),
('BN', 'en', 'English', 15),
('BT', 'en', 'English', 16),
('BW', 'en', 'English', 17),
('BY', 'en', 'English', 18),
('BZ', 'en', 'English', 19),
('CF', 'en', 'English', 20),
('CK', 'en', 'English', 21),
('CM', 'en', 'English', 22),
('CU', 'en', 'English', 23),
('CV', 'en', 'English', 24),
('DJ', 'en', 'English', 25),
('DM', 'en', 'English', 26),
('DZ', 'en', 'English', 27),
('ER', 'en', 'English', 28),
('ET', 'en', 'English', 29),
('FJ', 'en', 'English', 30),
('FK', 'en', 'English', 31),
('FM', 'en', 'English', 32),
('FO', 'en', 'English', 33),
('GA', 'en', 'English', 34),
('GD', 'en', 'English', 35),
('GE', 'en', 'English', 36),
('GG', 'en', 'English', 37),
('GH', 'en', 'English', 38),
('GI', 'en', 'English', 39),
('GL', 'en', 'English', 40),
('GM', 'en', 'English', 41),
('GN', 'en', 'English', 42),
('GQ', 'en', 'English', 43),
('GU', 'en', 'English', 44),
('GW', 'en', 'English', 45),
('GY', 'en', 'English', 46),
('IC', 'en', 'English', 47),
('IQ', 'en', 'English', 48),
('IR', 'en', 'English', 49),
('JE', 'en', 'English', 50),
('KG', 'en', 'English', 51),
('KH', 'en', 'English', 52),
('KI', 'en', 'English', 53),
('KM', 'en', 'English', 54),
('KN', 'en', 'English', 55),
('KP', 'en', 'English', 56),
('KV', 'en', 'English', 57),
('LA', 'en', 'English', 58),
('LC', 'en', 'English', 59),
('LI', 'en', 'English', 60),
('LR', 'en', 'English', 61),
('LS', 'en', 'English', 62),
('LY', 'en', 'English', 63),
('MA', 'en', 'English', 64),
('MC', 'en', 'English', 65),
('MD', 'en', 'English', 66),
('ME', 'en', 'English', 67),
('MH', 'en', 'English', 68),
('MK', 'en', 'English', 69),
('MM', 'en', 'English', 70),
('MN', 'en', 'English', 71),
('MO', 'en', 'English', 72),
('MP', 'en', 'English', 73),
('MR', 'en', 'English', 74),
('MS', 'en', 'English', 75),
('MV', 'en', 'English', 76),
('MW', 'en', 'English', 77),
('NC', 'en', 'English', 78),
('NE', 'en', 'English', 79),
('NP', 'en', 'English', 80),
('NR', 'en', 'English', 81),
('NU', 'en', 'English', 82),
('PF', 'en', 'English', 83),
('PG', 'en', 'English', 84),
('PR', 'en', 'English', 85),
('PW', 'en', 'English', 86),
('RE', 'en', 'English', 87),
('RW', 'en', 'English', 88),
('SB', 'en', 'English', 89),
('SC', 'en', 'English', 90),
('SD', 'en', 'English', 91),
('SH', 'en', 'English', 92),
('SL', 'en', 'English', 93),
('SM', 'en', 'English', 94),
('SO', 'en', 'English', 95),
('SR', 'en', 'English', 96),
('SS', 'en', 'English', 97),
('ST', 'en', 'English', 98),
('SY', 'en', 'English', 99),
('SZ', 'en', 'English', 100),
('TC', 'en', 'English', 101),
('TD', 'en', 'English', 102),
('TG', 'en', 'English', 103),
('TJ', 'en', 'English', 104),
('TL', 'en', 'English', 105),
('TN', 'en', 'English', 106),
('TO', 'en', 'English', 107),
('TV', 'en', 'English', 108),
('TZ', 'en', 'English', 109),
('UG', 'en', 'English', 110),
('US', 'en', 'English', 111),
('UZ', 'en', 'English', 112),
('VC', 'en', 'English', 113),
('VI', 'en', 'English', 114),
('VU', 'en', 'English', 115),
('WS', 'en', 'English', 116),
('XB', 'en', 'English', 117),
('XE', 'en', 'English', 118),
('XN', 'en', 'English', 119),
('XS', 'en', 'English', 120),
('XY', 'en', 'English', 121),
('YE', 'en', 'English', 122),
('YT', 'en', 'English', 123),
('AE', 'en', 'English', 124),
('AO', 'en', 'English', 125),
('AR', 'es', 'Spanish', 126),
('AR', 'en', 'English', 127),
('AT', 'de', 'German', 128),
('AT', 'en', 'English', 129),
('AU', 'en', 'English', 130),
('BB', 'en', 'English', 131),
('BD', 'en', 'English', 132),
('BE', 'en', 'English', 133),
('BE', 'fr', 'French', 134),
('BE', 'nl', 'Dutch', 135),
('BG', 'en', 'English', 136),
('BH', 'en', 'English', 137),
('BJ', 'fr', 'French', 138),
('BJ', 'en', 'English', 139),
('BM', 'en', 'English', 140),
('BO', 'es', 'Spanish', 141),
('BO', 'en', 'English', 142),
('BR', 'pt', 'Portuguese', 143),
('BR', 'en', 'English', 144),
('BS', 'en', 'English', 145),
('CA', 'en', 'English', 146),
('CA', 'fr', 'French', 147),
('CD', 'fr', 'French', 148),
('CD', 'en', 'English', 149),
('CG', 'fr', 'French', 150),
('CG', 'en', 'English', 151),
('CH', 'de', 'German', 152),
('CH', 'en', 'English', 153),
('CH', 'fr', 'French', 154),
('CH', 'it', 'Italian', 155),
('CI', 'en', 'English', 156),
('CI', 'fr', 'French', 157),
('CL', 'es', 'Spanish', 158),
('CL', 'en', 'English', 159),
('CN', 'zh', 'Chinese', 160),
('CN', 'en', 'English', 161),
('CO', 'es', 'Spanish', 162),
('CO', 'en', 'English', 163),
('CR', 'es', 'Spanish', 164),
('CR', 'en', 'English', 165),
('CY', 'el', 'Greek', 166),
('CY', 'en', 'English', 167),
('CZ', 'cs', 'Czech', 168),
('CZ', 'en', 'English', 169),
('DE', 'de', 'German', 170),
('DE', 'en', 'English', 171),
('DK', 'en', 'English', 172),
('DK', 'da', 'Danish', 173),
('DO', 'es', 'Spanish', 174),
('DO', 'en', 'English', 175),
('EC', 'es', 'Spanish', 176),
('EC', 'en', 'English', 177),
('EE', 'et', 'Estonian', 178),
('EE', 'en', 'English', 179),
('EE', 'ru', 'Russian', 180),
('EG', 'en', 'English', 181),
('ES', 'es', 'Spanish', 182),
('ES', 'en', 'English', 183),
('FI', 'en', 'English', 184),
('FR', 'fr', 'French', 185),
('FR', 'en', 'English', 186),
('GB', 'en', 'English', 187),
('GF', 'fr', 'French', 188),
('GF', 'en', 'English', 189),
('GP', 'en', 'English', 190),
('GP', 'fr', 'French', 191),
('GR', 'el', 'Greek', 192),
('GR', 'en', 'English', 193),
('GT', 'es', 'Spanish', 194),
('GT', 'en', 'English', 195),
('HK', 'en', 'English', 196),
('HK', 'sc', 'Simplified Chinese', 197),
('HK', 'tc', 'Traditional Chinese', 198),
('HN', 'es', 'Spanish', 199),
('HN', 'en', 'English', 200),
('HR', 'hr', 'Croatian', 201),
('HR', 'en', 'English', 202),
('HT', 'fr', 'French', 203),
('HT', 'en', 'English', 204),
('HU', 'hu', 'Hungarian', 205),
('HU', 'en', 'English', 206),
('ID', 'en', 'English', 207),
('ID', 'in', 'former Indonesian', 208),
('IE', 'en', 'English', 209),
('IL', 'en', 'English', 210),
('IN', 'en', 'English', 211),
('IS', 'en', 'English', 212),
('IS', 'is', 'Icelandic', 213),
('IT', 'it', 'Italian', 214),
('IT', 'en', 'English', 215),
('JM', 'en', 'English', 216),
('JO', 'en', 'English', 217),
('JP', 'ja', 'Japanese', 218),
('JP', 'en', 'English', 219),
('KE', 'en', 'English', 220),
('KR', 'ko', 'Korean', 221),
('KR', 'en', 'English', 222),
('KW', 'en', 'English', 223),
('KY', 'en', 'English', 224),
('KZ', 'en', 'English', 225),
('KZ', 'ru', 'Russian', 226),
('LB', 'en', 'English', 227),
('LK', 'en', 'English', 228),
('LT', 'lt', 'Lithuanian', 229),
('LT', 'en', 'English', 230),
('LU', 'de', 'German', 231),
('LU', 'fr', 'French', 232),
('LU', 'en', 'English', 233),
('LV', 'lv', 'Latvian, Lettish', 234),
('LV', 'en', 'English', 235),
('MG', 'fr', 'French', 236),
('MG', 'en', 'English', 237),
('ML', 'fr', 'French', 238),
('ML', 'en', 'English', 239),
('MQ', 'fr', 'French', 240),
('MQ', 'en', 'English', 241),
('MT', 'en', 'English', 242),
('MU', 'en', 'English', 243),
('MX', 'es', 'Spanish', 244),
('MX', 'en', 'English', 245),
('MY', 'en', 'English', 246),
('MZ', 'en', 'English', 247),
('NA', 'en', 'English', 248),
('NG', 'en', 'English', 249),
('NI', 'es', 'Spanish', 250),
('NI', 'en', 'English', 251),
('NL', 'nl', 'Dutch', 252),
('NL', 'en', 'English', 253),
('NO', 'en', 'English', 254),
('NZ', 'en', 'English', 255),
('OM', 'en', 'English', 256),
('PA', 'es', 'Spanish', 257),
('PA', 'en', 'English', 258),
('PE', 'en', 'English', 259),
('PE', 'es', 'Spanish', 260),
('PH', 'en', 'English', 261),
('PK', 'en', 'English', 262),
('PL', 'pl', 'Polish', 263),
('PL', 'en', 'English', 264),
('PT', 'pt', 'Portuguese', 265),
('PT', 'en', 'English', 266),
('PY', 'es', 'Spanish', 267),
('PY', 'en', 'English', 268),
('QA', 'en', 'English', 269),
('RO', 'en', 'English', 270),
('RO', 'ro', 'Romanian', 271),
('RS', 'sr', 'Serbian', 272),
('RS', 'en', 'English', 273),
('RU', 'ru', 'Russian', 274),
('RU', 'en', 'English', 275),
('SA', 'en', 'English', 276),
('SE', 'en', 'English', 277),
('SG', 'en', 'English', 278),
('SI', 'sl', 'Slovenian', 279),
('SI', 'en', 'English', 280),
('SK', 'sk', 'Slovak', 281),
('SK', 'en', 'English', 282),
('SN', 'fr', 'French', 283),
('SN', 'en', 'English', 284),
('SV', 'es', 'Spanish', 285),
('SV', 'en', 'English', 286),
('TH', 'th', 'Thai', 287),
('TH', 'en', 'English', 288),
('TR', 'en', 'English', 289),
('TR', 'tr', 'Turkish', 290),
('TT', 'en', 'English', 291),
('TW', 'zt', 'Chinese (Taiwan)', 292),
('TW', 'en', 'English', 293),
('UA', 'uk', 'Ukrainian', 294),
('UA', 'en', 'English', 295),
('UA', 'ru', 'Russian', 296),
('UY', 'es', 'Spanish', 297),
('UY', 'en', 'English', 298),
('VE', 'es', 'Spanish', 299),
('VE', 'en', 'English', 300),
('VG', 'en', 'English', 301),
('VN', 'en', 'English', 302),
('VN', 'vn', 'Vietnamese', 303),
('XC', 'en', 'English', 304),
('XM', 'en', 'English', 305),
('ZA', 'en', 'English', 306),
('ZM', 'en', 'English', 307),
('ZW', 'en', 'English', 308),
('EG', 'es', 'Spanish', 309),
('FI', 'fi', 'Finnish', 310),
('LV', 'ru', 'Russian', 311),
('BA', 'bs', 'Bosnian', 312),
('BG', 'bg', 'Bulgarian', 313),
('CM', 'fr', 'French', 314),
('DZ', 'fr', 'French', 315),
('MA', 'fr', 'French', 316),
('MZ', 'pt', 'Portuguese', 317),
('RE', 'fr', 'French', 318);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `dhl_language`
--
ALTER TABLE `dhl_language`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `dhl_language`
--
ALTER TABLE `dhl_language`
  MODIFY `id` int(11) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=319;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
